//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyTipoPaciente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPaciente", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class TipoPaciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_tipo {
            get {
                return this.cod_tipoField;
            }
            set {
                if ((this.cod_tipoField.Equals(value) != true)) {
                    this.cod_tipoField = value;
                    this.RaisePropertyChanged("cod_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_tipo {
            get {
                return this.nom_tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_tipoField, value) != true)) {
                    this.nom_tipoField = value;
                    this.RaisePropertyChanged("nom_tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyTipoPaciente.IServicioTipoPaciente")]
    public interface IServicioTipoPaciente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTipoPaciente/listarTipos", ReplyAction="http://tempuri.org/IServicioTipoPaciente/listarTiposResponse")]
        Win_Hunde.ProxyTipoPaciente.TipoPaciente[] listarTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTipoPaciente/listarTipos", ReplyAction="http://tempuri.org/IServicioTipoPaciente/listarTiposResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyTipoPaciente.TipoPaciente[]> listarTiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTipoPaciente/TipoPorRaza", ReplyAction="http://tempuri.org/IServicioTipoPaciente/TipoPorRazaResponse")]
        Win_Hunde.ProxyTipoPaciente.TipoPaciente TipoPorRaza(short codRaza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTipoPaciente/TipoPorRaza", ReplyAction="http://tempuri.org/IServicioTipoPaciente/TipoPorRazaResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyTipoPaciente.TipoPaciente> TipoPorRazaAsync(short codRaza);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioTipoPacienteChannel : Win_Hunde.ProxyTipoPaciente.IServicioTipoPaciente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTipoPacienteClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyTipoPaciente.IServicioTipoPaciente>, Win_Hunde.ProxyTipoPaciente.IServicioTipoPaciente {
        
        public ServicioTipoPacienteClient() {
        }
        
        public ServicioTipoPacienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTipoPacienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTipoPacienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTipoPacienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Win_Hunde.ProxyTipoPaciente.TipoPaciente[] listarTipos() {
            return base.Channel.listarTipos();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyTipoPaciente.TipoPaciente[]> listarTiposAsync() {
            return base.Channel.listarTiposAsync();
        }
        
        public Win_Hunde.ProxyTipoPaciente.TipoPaciente TipoPorRaza(short codRaza) {
            return base.Channel.TipoPorRaza(codRaza);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyTipoPaciente.TipoPaciente> TipoPorRazaAsync(short codRaza) {
            return base.Channel.TipoPorRazaAsync(codRaza);
        }
    }
}
