//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyConsulta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Consulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_citaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string color_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string condutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string est_nutricionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fec_consultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hora_consultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string raza_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_pacField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string actividad {
            get {
                return this.actividadField;
            }
            set {
                if ((object.ReferenceEquals(this.actividadField, value) != true)) {
                    this.actividadField = value;
                    this.RaisePropertyChanged("actividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_cita {
            get {
                return this.cod_citaField;
            }
            set {
                if ((this.cod_citaField.Equals(value) != true)) {
                    this.cod_citaField = value;
                    this.RaisePropertyChanged("cod_cita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_cli {
            get {
                return this.cod_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_cliField, value) != true)) {
                    this.cod_cliField = value;
                    this.RaisePropertyChanged("cod_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_emp {
            get {
                return this.cod_empField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_empField, value) != true)) {
                    this.cod_empField = value;
                    this.RaisePropertyChanged("cod_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_pac {
            get {
                return this.cod_pacField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_pacField, value) != true)) {
                    this.cod_pacField = value;
                    this.RaisePropertyChanged("cod_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string color_pac {
            get {
                return this.color_pacField;
            }
            set {
                if ((object.ReferenceEquals(this.color_pacField, value) != true)) {
                    this.color_pacField = value;
                    this.RaisePropertyChanged("color_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conduta {
            get {
                return this.condutaField;
            }
            set {
                if ((object.ReferenceEquals(this.condutaField, value) != true)) {
                    this.condutaField = value;
                    this.RaisePropertyChanged("conduta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string est_nutricional {
            get {
                return this.est_nutricionalField;
            }
            set {
                if ((object.ReferenceEquals(this.est_nutricionalField, value) != true)) {
                    this.est_nutricionalField = value;
                    this.RaisePropertyChanged("est_nutricional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fec_consulta {
            get {
                return this.fec_consultaField;
            }
            set {
                if ((object.ReferenceEquals(this.fec_consultaField, value) != true)) {
                    this.fec_consultaField = value;
                    this.RaisePropertyChanged("fec_consulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hora_consulta {
            get {
                return this.hora_consultaField;
            }
            set {
                if ((object.ReferenceEquals(this.hora_consultaField, value) != true)) {
                    this.hora_consultaField = value;
                    this.RaisePropertyChanged("hora_consulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cli {
            get {
                return this.nom_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_cliField, value) != true)) {
                    this.nom_cliField = value;
                    this.RaisePropertyChanged("nom_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_emp {
            get {
                return this.nom_empField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_empField, value) != true)) {
                    this.nom_empField = value;
                    this.RaisePropertyChanged("nom_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_pac {
            get {
                return this.nom_pacField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_pacField, value) != true)) {
                    this.nom_pacField = value;
                    this.RaisePropertyChanged("nom_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionesField, value) != true)) {
                    this.observacionesField = value;
                    this.RaisePropertyChanged("observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string raza_pac {
            get {
                return this.raza_pacField;
            }
            set {
                if ((object.ReferenceEquals(this.raza_pacField, value) != true)) {
                    this.raza_pacField = value;
                    this.RaisePropertyChanged("raza_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_pac {
            get {
                return this.tipo_pacField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_pacField, value) != true)) {
                    this.tipo_pacField = value;
                    this.RaisePropertyChanged("tipo_pac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cita", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Cita : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_citaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_citaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_citaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_reservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan hor_citaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_cita {
            get {
                return this.cod_citaField;
            }
            set {
                if ((this.cod_citaField.Equals(value) != true)) {
                    this.cod_citaField = value;
                    this.RaisePropertyChanged("cod_cita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_cli {
            get {
                return this.cod_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_cliField, value) != true)) {
                    this.cod_cliField = value;
                    this.RaisePropertyChanged("cod_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_cita {
            get {
                return this.est_citaField;
            }
            set {
                if ((this.est_citaField.Equals(value) != true)) {
                    this.est_citaField = value;
                    this.RaisePropertyChanged("est_cita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_cita {
            get {
                return this.fec_citaField;
            }
            set {
                if ((this.fec_citaField.Equals(value) != true)) {
                    this.fec_citaField = value;
                    this.RaisePropertyChanged("fec_cita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_reserva {
            get {
                return this.fec_reservaField;
            }
            set {
                if ((this.fec_reservaField.Equals(value) != true)) {
                    this.fec_reservaField = value;
                    this.RaisePropertyChanged("fec_reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan hor_cita {
            get {
                return this.hor_citaField;
            }
            set {
                if ((this.hor_citaField.Equals(value) != true)) {
                    this.hor_citaField = value;
                    this.RaisePropertyChanged("hor_cita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsulta.IServicioConsulta")]
    public interface IServicioConsulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorMascota", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorMascotaResponse")]
        Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorMascota(string codigoMascota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorMascota", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorMascotaResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorMascotaAsync(string codigoMascota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorMedico", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorMedicoResponse")]
        Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorMedico(string codigoMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorMedico", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorMedicoResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorMedicoAsync(string codigoMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorFecha", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorFechaResponse")]
        Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorFecha(System.DateTime fechaConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorFecha", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorFechaResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorFechaAsync(System.DateTime fechaConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/EntreFechas", ReplyAction="http://tempuri.org/IServicioConsulta/EntreFechasResponse")]
        Win_Hunde.ProxyConsulta.Consulta[] EntreFechas(System.DateTime fechaIni, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/EntreFechas", ReplyAction="http://tempuri.org/IServicioConsulta/EntreFechasResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> EntreFechasAsync(System.DateTime fechaIni, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorMascotaEntreFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorMascotaEntreFechasResponse")]
        Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorMascotaEntreFechas(string codigoMascota, System.DateTime fechaIni, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorMascotaEntreFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorMascotaEntreFechasResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorMascotaEntreFechasAsync(string codigoMascota, System.DateTime fechaIni, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorMedicoEntreFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorMedicoEntreFechasResponse")]
        Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorMedicoEntreFechas(string codigoMedico, System.DateTime fechaIni, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ConsultasPorMedicoEntreFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ConsultasPorMedicoEntreFechasResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorMedicoEntreFechasAsync(string codigoMedico, System.DateTime fechaIni, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ReservarCita", ReplyAction="http://tempuri.org/IServicioConsulta/ReservarCitaResponse")]
        bool ReservarCita(System.DateTime FechaHora, string codigoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ReservarCita", ReplyAction="http://tempuri.org/IServicioConsulta/ReservarCitaResponse")]
        System.Threading.Tasks.Task<bool> ReservarCitaAsync(System.DateTime FechaHora, string codigoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ActualizarReserva", ReplyAction="http://tempuri.org/IServicioConsulta/ActualizarReservaResponse")]
        bool ActualizarReserva(Win_Hunde.ProxyConsulta.Cita cita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ActualizarReserva", ReplyAction="http://tempuri.org/IServicioConsulta/ActualizarReservaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarReservaAsync(Win_Hunde.ProxyConsulta.Cita cita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/CancelarReserva", ReplyAction="http://tempuri.org/IServicioConsulta/CancelarReservaResponse")]
        bool CancelarReserva(short codigoCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/CancelarReserva", ReplyAction="http://tempuri.org/IServicioConsulta/CancelarReservaResponse")]
        System.Threading.Tasks.Task<bool> CancelarReservaAsync(short codigoCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/GenerarConsulta", ReplyAction="http://tempuri.org/IServicioConsulta/GenerarConsultaResponse")]
        bool GenerarConsulta(string codigoPaciente, string codigoEmpleado, short codigoCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/GenerarConsulta", ReplyAction="http://tempuri.org/IServicioConsulta/GenerarConsultaResponse")]
        System.Threading.Tasks.Task<bool> GenerarConsultaAsync(string codigoPaciente, string codigoEmpleado, short codigoCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/CancelarConsulta", ReplyAction="http://tempuri.org/IServicioConsulta/CancelarConsultaResponse")]
        bool CancelarConsulta(short codigoConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/CancelarConsulta", ReplyAction="http://tempuri.org/IServicioConsulta/CancelarConsultaResponse")]
        System.Threading.Tasks.Task<bool> CancelarConsultaAsync(short codigoConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/AgregarDetallesDeConsulta", ReplyAction="http://tempuri.org/IServicioConsulta/AgregarDetallesDeConsultaResponse")]
        bool AgregarDetallesDeConsulta(short codigoConsulta, short codigoTratamiento, short codigoEstado, short codigoMedicina, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/AgregarDetallesDeConsulta", ReplyAction="http://tempuri.org/IServicioConsulta/AgregarDetallesDeConsultaResponse")]
        System.Threading.Tasks.Task<bool> AgregarDetallesDeConsultaAsync(short codigoConsulta, short codigoTratamiento, short codigoEstado, short codigoMedicina, string observaciones);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultaChannel : Win_Hunde.ProxyConsulta.IServicioConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultaClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyConsulta.IServicioConsulta>, Win_Hunde.ProxyConsulta.IServicioConsulta {
        
        public ServicioConsultaClient() {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorMascota(string codigoMascota) {
            return base.Channel.ConsultasPorMascota(codigoMascota);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorMascotaAsync(string codigoMascota) {
            return base.Channel.ConsultasPorMascotaAsync(codigoMascota);
        }
        
        public Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorMedico(string codigoMedico) {
            return base.Channel.ConsultasPorMedico(codigoMedico);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorMedicoAsync(string codigoMedico) {
            return base.Channel.ConsultasPorMedicoAsync(codigoMedico);
        }
        
        public Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorFecha(System.DateTime fechaConsulta) {
            return base.Channel.ConsultasPorFecha(fechaConsulta);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorFechaAsync(System.DateTime fechaConsulta) {
            return base.Channel.ConsultasPorFechaAsync(fechaConsulta);
        }
        
        public Win_Hunde.ProxyConsulta.Consulta[] EntreFechas(System.DateTime fechaIni, System.DateTime fechaFin) {
            return base.Channel.EntreFechas(fechaIni, fechaFin);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> EntreFechasAsync(System.DateTime fechaIni, System.DateTime fechaFin) {
            return base.Channel.EntreFechasAsync(fechaIni, fechaFin);
        }
        
        public Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorMascotaEntreFechas(string codigoMascota, System.DateTime fechaIni, System.DateTime fechaFin) {
            return base.Channel.ConsultasPorMascotaEntreFechas(codigoMascota, fechaIni, fechaFin);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorMascotaEntreFechasAsync(string codigoMascota, System.DateTime fechaIni, System.DateTime fechaFin) {
            return base.Channel.ConsultasPorMascotaEntreFechasAsync(codigoMascota, fechaIni, fechaFin);
        }
        
        public Win_Hunde.ProxyConsulta.Consulta[] ConsultasPorMedicoEntreFechas(string codigoMedico, System.DateTime fechaIni, System.DateTime fechaFin) {
            return base.Channel.ConsultasPorMedicoEntreFechas(codigoMedico, fechaIni, fechaFin);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyConsulta.Consulta[]> ConsultasPorMedicoEntreFechasAsync(string codigoMedico, System.DateTime fechaIni, System.DateTime fechaFin) {
            return base.Channel.ConsultasPorMedicoEntreFechasAsync(codigoMedico, fechaIni, fechaFin);
        }
        
        public bool ReservarCita(System.DateTime FechaHora, string codigoCliente) {
            return base.Channel.ReservarCita(FechaHora, codigoCliente);
        }
        
        public System.Threading.Tasks.Task<bool> ReservarCitaAsync(System.DateTime FechaHora, string codigoCliente) {
            return base.Channel.ReservarCitaAsync(FechaHora, codigoCliente);
        }
        
        public bool ActualizarReserva(Win_Hunde.ProxyConsulta.Cita cita) {
            return base.Channel.ActualizarReserva(cita);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarReservaAsync(Win_Hunde.ProxyConsulta.Cita cita) {
            return base.Channel.ActualizarReservaAsync(cita);
        }
        
        public bool CancelarReserva(short codigoCita) {
            return base.Channel.CancelarReserva(codigoCita);
        }
        
        public System.Threading.Tasks.Task<bool> CancelarReservaAsync(short codigoCita) {
            return base.Channel.CancelarReservaAsync(codigoCita);
        }
        
        public bool GenerarConsulta(string codigoPaciente, string codigoEmpleado, short codigoCita) {
            return base.Channel.GenerarConsulta(codigoPaciente, codigoEmpleado, codigoCita);
        }
        
        public System.Threading.Tasks.Task<bool> GenerarConsultaAsync(string codigoPaciente, string codigoEmpleado, short codigoCita) {
            return base.Channel.GenerarConsultaAsync(codigoPaciente, codigoEmpleado, codigoCita);
        }
        
        public bool CancelarConsulta(short codigoConsulta) {
            return base.Channel.CancelarConsulta(codigoConsulta);
        }
        
        public System.Threading.Tasks.Task<bool> CancelarConsultaAsync(short codigoConsulta) {
            return base.Channel.CancelarConsultaAsync(codigoConsulta);
        }
        
        public bool AgregarDetallesDeConsulta(short codigoConsulta, short codigoTratamiento, short codigoEstado, short codigoMedicina, string observaciones) {
            return base.Channel.AgregarDetallesDeConsulta(codigoConsulta, codigoTratamiento, codigoEstado, codigoMedicina, observaciones);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarDetallesDeConsultaAsync(short codigoConsulta, short codigoTratamiento, short codigoEstado, short codigoMedicina, string observaciones) {
            return base.Channel.AgregarDetallesDeConsultaAsync(codigoConsulta, codigoTratamiento, codigoEstado, codigoMedicina, observaciones);
        }
    }
}
