//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyPaciente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class PacienteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_nac_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_pacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Ult_vis_pacField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_pac {
            get {
                return this.Cod_pacField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_pacField, value) != true)) {
                    this.Cod_pacField = value;
                    this.RaisePropertyChanged("Cod_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_pac {
            get {
                return this.Est_pacField;
            }
            set {
                if ((this.Est_pacField.Equals(value) != true)) {
                    this.Est_pacField = value;
                    this.RaisePropertyChanged("Est_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nac_pac {
            get {
                return this.Fec_nac_pacField;
            }
            set {
                if ((this.Fec_nac_pacField.Equals(value) != true)) {
                    this.Fec_nac_pacField = value;
                    this.RaisePropertyChanged("Fec_nac_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_pac {
            get {
                return this.Nom_pacField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_pacField, value) != true)) {
                    this.Nom_pacField = value;
                    this.RaisePropertyChanged("Nom_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((this.PesoField.Equals(value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raza {
            get {
                return this.RazaField;
            }
            set {
                if ((object.ReferenceEquals(this.RazaField, value) != true)) {
                    this.RazaField = value;
                    this.RaisePropertyChanged("Raza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_pac {
            get {
                return this.Tipo_pacField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_pacField, value) != true)) {
                    this.Tipo_pacField = value;
                    this.RaisePropertyChanged("Tipo_pac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ult_vis_pac {
            get {
                return this.Ult_vis_pacField;
            }
            set {
                if ((this.Ult_vis_pacField.Equals(value) != true)) {
                    this.Ult_vis_pacField = value;
                    this.RaisePropertyChanged("Ult_vis_pac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPaciente.IServicioPaciente")]
    public interface IServicioPaciente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorRaza", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorRazaResponse")]
        Win_Hunde.ProxyPaciente.PacienteBE[] ConsultarPacientesPorRaza(string strRazaPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorRaza", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorRazaResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyPaciente.PacienteBE[]> ConsultarPacientesPorRazaAsync(string strRazaPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorFecha", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorFechaResponse")]
        Win_Hunde.ProxyPaciente.PacienteBE[] ConsultarPacientesPorFecha(string strCod, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorFecha", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorFechaResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyPaciente.PacienteBE[]> ConsultarPacientesPorFechaAsync(string strCod, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorTratamiento", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorTratamientoResponse")]
        Win_Hunde.ProxyPaciente.PacienteBE[] ConsultarPacientesPorTratamiento(string strTipoTratamiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorTratamiento", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacientesPorTratamientoResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyPaciente.PacienteBE[]> ConsultarPacientesPorTratamientoAsync(string strTipoTratamiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPacienteChannel : Win_Hunde.ProxyPaciente.IServicioPaciente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPacienteClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyPaciente.IServicioPaciente>, Win_Hunde.ProxyPaciente.IServicioPaciente {
        
        public ServicioPacienteClient() {
        }
        
        public ServicioPacienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPacienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPacienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPacienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Win_Hunde.ProxyPaciente.PacienteBE[] ConsultarPacientesPorRaza(string strRazaPaciente) {
            return base.Channel.ConsultarPacientesPorRaza(strRazaPaciente);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyPaciente.PacienteBE[]> ConsultarPacientesPorRazaAsync(string strRazaPaciente) {
            return base.Channel.ConsultarPacientesPorRazaAsync(strRazaPaciente);
        }
        
        public Win_Hunde.ProxyPaciente.PacienteBE[] ConsultarPacientesPorFecha(string strCod, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ConsultarPacientesPorFecha(strCod, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyPaciente.PacienteBE[]> ConsultarPacientesPorFechaAsync(string strCod, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ConsultarPacientesPorFechaAsync(strCod, fecini, fecfin);
        }
        
        public Win_Hunde.ProxyPaciente.PacienteBE[] ConsultarPacientesPorTratamiento(string strTipoTratamiento) {
            return base.Channel.ConsultarPacientesPorTratamiento(strTipoTratamiento);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyPaciente.PacienteBE[]> ConsultarPacientesPorTratamientoAsync(string strTipoTratamiento) {
            return base.Channel.ConsultarPacientesPorTratamientoAsync(strTipoTratamiento);
        }
    }
}
