//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_supervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dir_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string email_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estado_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_reg_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ult_modificacion_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_ubigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short sueldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string supField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short tipo_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string us_ureg_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usu_ult_modificacion_empField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_emp {
            get {
                return this.ape_empField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_empField, value) != true)) {
                    this.ape_empField = value;
                    this.RaisePropertyChanged("ape_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_emp {
            get {
                return this.cod_empField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_empField, value) != true)) {
                    this.cod_empField = value;
                    this.RaisePropertyChanged("cod_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_rol {
            get {
                return this.cod_rolField;
            }
            set {
                if ((this.cod_rolField.Equals(value) != true)) {
                    this.cod_rolField = value;
                    this.RaisePropertyChanged("cod_rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_supervisor {
            get {
                return this.cod_supervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_supervisorField, value) != true)) {
                    this.cod_supervisorField = value;
                    this.RaisePropertyChanged("cod_supervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentoField, value) != true)) {
                    this.departamentoField = value;
                    this.RaisePropertyChanged("departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir_emp {
            get {
                return this.dir_empField;
            }
            set {
                if ((object.ReferenceEquals(this.dir_empField, value) != true)) {
                    this.dir_empField = value;
                    this.RaisePropertyChanged("dir_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.distritoField, value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email_emp {
            get {
                return this.email_empField;
            }
            set {
                if ((object.ReferenceEquals(this.email_empField, value) != true)) {
                    this.email_empField = value;
                    this.RaisePropertyChanged("email_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado_emp {
            get {
                return this.estado_empField;
            }
            set {
                if ((this.estado_empField.Equals(value) != true)) {
                    this.estado_empField = value;
                    this.RaisePropertyChanged("estado_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                if ((this.fecha_ingresoField.Equals(value) != true)) {
                    this.fecha_ingresoField = value;
                    this.RaisePropertyChanged("fecha_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_reg_emp {
            get {
                return this.fecha_reg_empField;
            }
            set {
                if ((this.fecha_reg_empField.Equals(value) != true)) {
                    this.fecha_reg_empField = value;
                    this.RaisePropertyChanged("fecha_reg_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ult_modificacion_emp {
            get {
                return this.fecha_ult_modificacion_empField;
            }
            set {
                if ((this.fecha_ult_modificacion_empField.Equals(value) != true)) {
                    this.fecha_ult_modificacion_empField = value;
                    this.RaisePropertyChanged("fecha_ult_modificacion_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_ubigeo {
            get {
                return this.id_ubigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_ubigeoField, value) != true)) {
                    this.id_ubigeoField = value;
                    this.RaisePropertyChanged("id_ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_ape {
            get {
                return this.nom_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_apeField, value) != true)) {
                    this.nom_apeField = value;
                    this.RaisePropertyChanged("nom_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_emp {
            get {
                return this.nom_empField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_empField, value) != true)) {
                    this.nom_empField = value;
                    this.RaisePropertyChanged("nom_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                if ((object.ReferenceEquals(this.rolField, value) != true)) {
                    this.rolField = value;
                    this.RaisePropertyChanged("rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short sueldo {
            get {
                return this.sueldoField;
            }
            set {
                if ((this.sueldoField.Equals(value) != true)) {
                    this.sueldoField = value;
                    this.RaisePropertyChanged("sueldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sup {
            get {
                return this.supField;
            }
            set {
                if ((object.ReferenceEquals(this.supField, value) != true)) {
                    this.supField = value;
                    this.RaisePropertyChanged("sup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short tipo_emp {
            get {
                return this.tipo_empField;
            }
            set {
                if ((this.tipo_empField.Equals(value) != true)) {
                    this.tipo_empField = value;
                    this.RaisePropertyChanged("tipo_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string us_ureg_emp {
            get {
                return this.us_ureg_empField;
            }
            set {
                if ((object.ReferenceEquals(this.us_ureg_empField, value) != true)) {
                    this.us_ureg_empField = value;
                    this.RaisePropertyChanged("us_ureg_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usu_ult_modificacion_emp {
            get {
                return this.usu_ult_modificacion_empField;
            }
            set {
                if ((object.ReferenceEquals(this.usu_ult_modificacion_empField, value) != true)) {
                    this.usu_ult_modificacion_empField = value;
                    this.RaisePropertyChanged("usu_ult_modificacion_emp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEmpleado.IServicioEmpleado")]
    public interface IServicioEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/InsertarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/InsertarEmpleadoResponse")]
        bool InsertarEmpleado(Win_Hunde.ProxyEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/InsertarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/InsertarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> InsertarEmpleadoAsync(Win_Hunde.ProxyEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ConsultarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ConsultarEmpleadoResponse")]
        Win_Hunde.ProxyEmpleado.Empleado ConsultarEmpleado(string codEmpl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ConsultarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ConsultarEmpleadoResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyEmpleado.Empleado> ConsultarEmpleadoAsync(string codEmpl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ActualizarEmpleadoResponse")]
        bool ActualizarEmpleado(Win_Hunde.ProxyEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ActualizarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEmpleadoAsync(Win_Hunde.ProxyEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/EliminarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/EliminarEmpleadoResponse")]
        bool EliminarEmpleado(string codEmpl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/EliminarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/EliminarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> EliminarEmpleadoAsync(string codEmpl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ListarEmpleados", ReplyAction="http://tempuri.org/IServicioEmpleado/ListarEmpleadosResponse")]
        Win_Hunde.ProxyEmpleado.Empleado[] ListarEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ListarEmpleados", ReplyAction="http://tempuri.org/IServicioEmpleado/ListarEmpleadosResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyEmpleado.Empleado[]> ListarEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ListarSupervisores", ReplyAction="http://tempuri.org/IServicioEmpleado/ListarSupervisoresResponse")]
        Win_Hunde.ProxyEmpleado.Empleado[] ListarSupervisores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ListarSupervisores", ReplyAction="http://tempuri.org/IServicioEmpleado/ListarSupervisoresResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyEmpleado.Empleado[]> ListarSupervisoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/EmpleadosPorDepartamento", ReplyAction="http://tempuri.org/IServicioEmpleado/EmpleadosPorDepartamentoResponse")]
        Win_Hunde.ProxyEmpleado.Empleado[] EmpleadosPorDepartamento(string idDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/EmpleadosPorDepartamento", ReplyAction="http://tempuri.org/IServicioEmpleado/EmpleadosPorDepartamentoResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyEmpleado.Empleado[]> EmpleadosPorDepartamentoAsync(string idDepa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEmpleadoChannel : Win_Hunde.ProxyEmpleado.IServicioEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEmpleadoClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyEmpleado.IServicioEmpleado>, Win_Hunde.ProxyEmpleado.IServicioEmpleado {
        
        public ServicioEmpleadoClient() {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarEmpleado(Win_Hunde.ProxyEmpleado.Empleado empleado) {
            return base.Channel.InsertarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarEmpleadoAsync(Win_Hunde.ProxyEmpleado.Empleado empleado) {
            return base.Channel.InsertarEmpleadoAsync(empleado);
        }
        
        public Win_Hunde.ProxyEmpleado.Empleado ConsultarEmpleado(string codEmpl) {
            return base.Channel.ConsultarEmpleado(codEmpl);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyEmpleado.Empleado> ConsultarEmpleadoAsync(string codEmpl) {
            return base.Channel.ConsultarEmpleadoAsync(codEmpl);
        }
        
        public bool ActualizarEmpleado(Win_Hunde.ProxyEmpleado.Empleado empleado) {
            return base.Channel.ActualizarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEmpleadoAsync(Win_Hunde.ProxyEmpleado.Empleado empleado) {
            return base.Channel.ActualizarEmpleadoAsync(empleado);
        }
        
        public bool EliminarEmpleado(string codEmpl) {
            return base.Channel.EliminarEmpleado(codEmpl);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEmpleadoAsync(string codEmpl) {
            return base.Channel.EliminarEmpleadoAsync(codEmpl);
        }
        
        public Win_Hunde.ProxyEmpleado.Empleado[] ListarEmpleados() {
            return base.Channel.ListarEmpleados();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyEmpleado.Empleado[]> ListarEmpleadosAsync() {
            return base.Channel.ListarEmpleadosAsync();
        }
        
        public Win_Hunde.ProxyEmpleado.Empleado[] ListarSupervisores() {
            return base.Channel.ListarSupervisores();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyEmpleado.Empleado[]> ListarSupervisoresAsync() {
            return base.Channel.ListarSupervisoresAsync();
        }
        
        public Win_Hunde.ProxyEmpleado.Empleado[] EmpleadosPorDepartamento(string idDepa) {
            return base.Channel.EmpleadosPorDepartamento(idDepa);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyEmpleado.Empleado[]> EmpleadosPorDepartamentoAsync(string idDepa) {
            return base.Channel.EmpleadosPorDepartamentoAsync(idDepa);
        }
    }
}
