//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyUbigeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ubigeo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Ubigeo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_depaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_distField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentoField, value) != true)) {
                    this.departamentoField = value;
                    this.RaisePropertyChanged("departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.distritoField, value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_Ubigeo {
            get {
                return this.id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_UbigeoField, value) != true)) {
                    this.id_UbigeoField = value;
                    this.RaisePropertyChanged("id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_depa {
            get {
                return this.id_depaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_depaField, value) != true)) {
                    this.id_depaField = value;
                    this.RaisePropertyChanged("id_depa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_dist {
            get {
                return this.id_distField;
            }
            set {
                if ((object.ReferenceEquals(this.id_distField, value) != true)) {
                    this.id_distField = value;
                    this.RaisePropertyChanged("id_dist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_prov {
            get {
                return this.id_provField;
            }
            set {
                if ((object.ReferenceEquals(this.id_provField, value) != true)) {
                    this.id_provField = value;
                    this.RaisePropertyChanged("id_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbigeo.IServicioUbigeo")]
    public interface IServicioUbigeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/UbigeoDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/UbigeoDepartamentosResponse")]
        Win_Hunde.ProxyUbigeo.Ubigeo[] UbigeoDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/UbigeoDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/UbigeoDepartamentosResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyUbigeo.Ubigeo[]> UbigeoDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_ProvinciasDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_ProvinciasDepartamentoResponse")]
        Win_Hunde.ProxyUbigeo.Ubigeo[] Ubigeo_ProvinciasDepartamento(string idDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_ProvinciasDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_ProvinciasDepartamentoResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyUbigeo.Ubigeo[]> Ubigeo_ProvinciasDepartamentoAsync(string idDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_DistritosProvinciaDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_DistritosProvinciaDepartamentoResponse")]
        Win_Hunde.ProxyUbigeo.Ubigeo[] Ubigeo_DistritosProvinciaDepartamento(string idDepa, string idProv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_DistritosProvinciaDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_DistritosProvinciaDepartamentoResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyUbigeo.Ubigeo[]> Ubigeo_DistritosProvinciaDepartamentoAsync(string idDepa, string idProv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUbigeoChannel : Win_Hunde.ProxyUbigeo.IServicioUbigeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyUbigeo.IServicioUbigeo>, Win_Hunde.ProxyUbigeo.IServicioUbigeo {
        
        public ServicioUbigeoClient() {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Win_Hunde.ProxyUbigeo.Ubigeo[] UbigeoDepartamentos() {
            return base.Channel.UbigeoDepartamentos();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyUbigeo.Ubigeo[]> UbigeoDepartamentosAsync() {
            return base.Channel.UbigeoDepartamentosAsync();
        }
        
        public Win_Hunde.ProxyUbigeo.Ubigeo[] Ubigeo_ProvinciasDepartamento(string idDepa) {
            return base.Channel.Ubigeo_ProvinciasDepartamento(idDepa);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyUbigeo.Ubigeo[]> Ubigeo_ProvinciasDepartamentoAsync(string idDepa) {
            return base.Channel.Ubigeo_ProvinciasDepartamentoAsync(idDepa);
        }
        
        public Win_Hunde.ProxyUbigeo.Ubigeo[] Ubigeo_DistritosProvinciaDepartamento(string idDepa, string idProv) {
            return base.Channel.Ubigeo_DistritosProvinciaDepartamento(idDepa, idProv);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyUbigeo.Ubigeo[]> Ubigeo_DistritosProvinciaDepartamentoAsync(string idDepa, string idProv) {
            return base.Channel.Ubigeo_DistritosProvinciaDepartamentoAsync(idDepa, idProv);
        }
    }
}
