//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyColor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Color", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Color : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_colorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_color {
            get {
                return this.cod_colorField;
            }
            set {
                if ((this.cod_colorField.Equals(value) != true)) {
                    this.cod_colorField = value;
                    this.RaisePropertyChanged("cod_color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_color {
            get {
                return this.nom_colorField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_colorField, value) != true)) {
                    this.nom_colorField = value;
                    this.RaisePropertyChanged("nom_color");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyColor.IServicioColor")]
    public interface IServicioColor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioColor/ListarColores", ReplyAction="http://tempuri.org/IServicioColor/ListarColoresResponse")]
        Win_Hunde.ProxyColor.Color[] ListarColores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioColor/ListarColores", ReplyAction="http://tempuri.org/IServicioColor/ListarColoresResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyColor.Color[]> ListarColoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioColorChannel : Win_Hunde.ProxyColor.IServicioColor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioColorClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyColor.IServicioColor>, Win_Hunde.ProxyColor.IServicioColor {
        
        public ServicioColorClient() {
        }
        
        public ServicioColorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioColorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioColorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioColorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Win_Hunde.ProxyColor.Color[] ListarColores() {
            return base.Channel.ListarColores();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyColor.Color[]> ListarColoresAsync() {
            return base.Channel.ListarColoresAsync();
        }
    }
}
