//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyProveedor1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProveedorBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class ProveedorBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_medField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccion_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string email_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estado_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_reg_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_medicinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rep_ven_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ruc_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_medicinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_med {
            get {
                return this.cod_medField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_medField, value) != true)) {
                    this.cod_medField = value;
                    this.RaisePropertyChanged("cod_med");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_prov {
            get {
                return this.cod_provField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_provField, value) != true)) {
                    this.cod_provField = value;
                    this.RaisePropertyChanged("cod_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion_prov {
            get {
                return this.direccion_provField;
            }
            set {
                if ((object.ReferenceEquals(this.direccion_provField, value) != true)) {
                    this.direccion_provField = value;
                    this.RaisePropertyChanged("direccion_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email_prov {
            get {
                return this.email_provField;
            }
            set {
                if ((object.ReferenceEquals(this.email_provField, value) != true)) {
                    this.email_provField = value;
                    this.RaisePropertyChanged("email_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado_prov {
            get {
                return this.estado_provField;
            }
            set {
                if ((this.estado_provField.Equals(value) != true)) {
                    this.estado_provField = value;
                    this.RaisePropertyChanged("estado_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_reg_prov {
            get {
                return this.fec_reg_provField;
            }
            set {
                if ((this.fec_reg_provField.Equals(value) != true)) {
                    this.fec_reg_provField = value;
                    this.RaisePropertyChanged("fec_reg_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_prov {
            get {
                return this.nom_provField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_provField, value) != true)) {
                    this.nom_provField = value;
                    this.RaisePropertyChanged("nom_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre_medicina {
            get {
                return this.nombre_medicinaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_medicinaField, value) != true)) {
                    this.nombre_medicinaField = value;
                    this.RaisePropertyChanged("nombre_medicina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rep_ven_prov {
            get {
                return this.rep_ven_provField;
            }
            set {
                if ((object.ReferenceEquals(this.rep_ven_provField, value) != true)) {
                    this.rep_ven_provField = value;
                    this.RaisePropertyChanged("rep_ven_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruc_prov {
            get {
                return this.ruc_provField;
            }
            set {
                if ((object.ReferenceEquals(this.ruc_provField, value) != true)) {
                    this.ruc_provField = value;
                    this.RaisePropertyChanged("ruc_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_prov {
            get {
                return this.tel_provField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_provField, value) != true)) {
                    this.tel_provField = value;
                    this.RaisePropertyChanged("tel_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_medicina {
            get {
                return this.tipo_medicinaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_medicinaField, value) != true)) {
                    this.tipo_medicinaField = value;
                    this.RaisePropertyChanged("tipo_medicina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadosBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class EstadosBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_medField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estado_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_medicinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_medicinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_med {
            get {
                return this.cod_medField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_medField, value) != true)) {
                    this.cod_medField = value;
                    this.RaisePropertyChanged("cod_med");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_prov {
            get {
                return this.cod_provField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_provField, value) != true)) {
                    this.cod_provField = value;
                    this.RaisePropertyChanged("cod_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado_prov {
            get {
                return this.estado_provField;
            }
            set {
                if ((this.estado_provField.Equals(value) != true)) {
                    this.estado_provField = value;
                    this.RaisePropertyChanged("estado_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_prov {
            get {
                return this.nom_provField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_provField, value) != true)) {
                    this.nom_provField = value;
                    this.RaisePropertyChanged("nom_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre_medicina {
            get {
                return this.nombre_medicinaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_medicinaField, value) != true)) {
                    this.nombre_medicinaField = value;
                    this.RaisePropertyChanged("nombre_medicina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_medicina {
            get {
                return this.tipo_medicinaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_medicinaField, value) != true)) {
                    this.tipo_medicinaField = value;
                    this.RaisePropertyChanged("tipo_medicina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyProveedor1.IServicioProveedor")]
    public interface IServicioProveedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarProveedores", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarProveedoresResponse")]
        Win_Hunde.ProxyProveedor1.ProveedorBE[] ConsultarProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarProveedores", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarProveedoresResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.ProveedorBE[]> ConsultarProveedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarProveedorPorCodigo", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarProveedorPorCodigoResponse")]
        Win_Hunde.ProxyProveedor1.ProveedorBE ConsultarProveedorPorCodigo(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarProveedorPorCodigo", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarProveedorPorCodigoResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.ProveedorBE> ConsultarProveedorPorCodigoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarSupervisor", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarSupervisorResponse")]
        Win_Hunde.ProxyProveedor1.ProveedorBE[] ConsultarSupervisor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarSupervisor", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarSupervisorResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.ProveedorBE[]> ConsultarSupervisorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarMedicinaProveedor", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarMedicinaProveedorResponse")]
        Win_Hunde.ProxyProveedor1.ProveedorBE[] ConsultarMedicinaProveedor(string srtTipoMedicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarMedicinaProveedor", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarMedicinaProveedorResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.ProveedorBE[]> ConsultarMedicinaProveedorAsync(string srtTipoMedicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarEstadoProveedorMedicina", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarEstadoProveedorMedicinaResponse")]
        Win_Hunde.ProxyProveedor1.EstadosBE[] ConsultarEstadoProveedorMedicina(short strEstadoProveedor, string strTipoMedicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProveedor/ConsultarEstadoProveedorMedicina", ReplyAction="http://tempuri.org/IServicioProveedor/ConsultarEstadoProveedorMedicinaResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.EstadosBE[]> ConsultarEstadoProveedorMedicinaAsync(short strEstadoProveedor, string strTipoMedicina);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioProveedorChannel : Win_Hunde.ProxyProveedor1.IServicioProveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProveedorClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyProveedor1.IServicioProveedor>, Win_Hunde.ProxyProveedor1.IServicioProveedor {
        
        public ServicioProveedorClient() {
        }
        
        public ServicioProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Win_Hunde.ProxyProveedor1.ProveedorBE[] ConsultarProveedores() {
            return base.Channel.ConsultarProveedores();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.ProveedorBE[]> ConsultarProveedoresAsync() {
            return base.Channel.ConsultarProveedoresAsync();
        }
        
        public Win_Hunde.ProxyProveedor1.ProveedorBE ConsultarProveedorPorCodigo(string strCodigo) {
            return base.Channel.ConsultarProveedorPorCodigo(strCodigo);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.ProveedorBE> ConsultarProveedorPorCodigoAsync(string strCodigo) {
            return base.Channel.ConsultarProveedorPorCodigoAsync(strCodigo);
        }
        
        public Win_Hunde.ProxyProveedor1.ProveedorBE[] ConsultarSupervisor() {
            return base.Channel.ConsultarSupervisor();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.ProveedorBE[]> ConsultarSupervisorAsync() {
            return base.Channel.ConsultarSupervisorAsync();
        }
        
        public Win_Hunde.ProxyProveedor1.ProveedorBE[] ConsultarMedicinaProveedor(string srtTipoMedicina) {
            return base.Channel.ConsultarMedicinaProveedor(srtTipoMedicina);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.ProveedorBE[]> ConsultarMedicinaProveedorAsync(string srtTipoMedicina) {
            return base.Channel.ConsultarMedicinaProveedorAsync(srtTipoMedicina);
        }
        
        public Win_Hunde.ProxyProveedor1.EstadosBE[] ConsultarEstadoProveedorMedicina(short strEstadoProveedor, string strTipoMedicina) {
            return base.Channel.ConsultarEstadoProveedorMedicina(strEstadoProveedor, strTipoMedicina);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyProveedor1.EstadosBE[]> ConsultarEstadoProveedorMedicinaAsync(short strEstadoProveedor, string strTipoMedicina) {
            return base.Channel.ConsultarEstadoProveedorMedicinaAsync(strEstadoProveedor, strTipoMedicina);
        }
    }
}
