//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hunde
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HundeDBEntities : DbContext
    {
        public HundeDBEntities()
            : base("name=HundeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Cita> Tb_Cita { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_Color> Tb_Color { get; set; }
        public virtual DbSet<Tb_Empleado> Tb_Empleado { get; set; }
        public virtual DbSet<Tb_Estado> Tb_Estado { get; set; }
        public virtual DbSet<Tb_Medicina> Tb_Medicina { get; set; }
        public virtual DbSet<Tb_Paciente> Tb_Paciente { get; set; }
        public virtual DbSet<Tb_Proveedor> Tb_Proveedor { get; set; }
        public virtual DbSet<Tb_Raza> Tb_Raza { get; set; }
        public virtual DbSet<Tb_Rol> Tb_Rol { get; set; }
        public virtual DbSet<Tb_Tipo_Paciente> Tb_Tipo_Paciente { get; set; }
        public virtual DbSet<Tb_Tratamiento> Tb_Tratamiento { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<vw_Consultas> vw_Consultas { get; set; }
        public virtual DbSet<vw_DetallesPaciente> vw_DetallesPaciente { get; set; }
        public virtual DbSet<vw_ConsultaDetallada> vw_ConsultaDetallada { get; set; }
        public virtual DbSet<Tb_Consulta> Tb_Consulta { get; set; }
        public virtual DbSet<Tb_Detalle_Consulta> Tb_Detalle_Consulta { get; set; }
    
        public virtual int usp_ActualizarCliente(string vnom_cliente, string vape_cli, string vdir_cli, string vcel_cli, string vemail_cli, Nullable<int> ves_dueno, string vid_ubigeo, string vdni_cli, string vusu_ult_mod, Nullable<int> vestado_cli, string vcod_cli)
        {
            var vnom_clienteParameter = vnom_cliente != null ?
                new ObjectParameter("vnom_cliente", vnom_cliente) :
                new ObjectParameter("vnom_cliente", typeof(string));
    
            var vape_cliParameter = vape_cli != null ?
                new ObjectParameter("vape_cli", vape_cli) :
                new ObjectParameter("vape_cli", typeof(string));
    
            var vdir_cliParameter = vdir_cli != null ?
                new ObjectParameter("vdir_cli", vdir_cli) :
                new ObjectParameter("vdir_cli", typeof(string));
    
            var vcel_cliParameter = vcel_cli != null ?
                new ObjectParameter("vcel_cli", vcel_cli) :
                new ObjectParameter("vcel_cli", typeof(string));
    
            var vemail_cliParameter = vemail_cli != null ?
                new ObjectParameter("vemail_cli", vemail_cli) :
                new ObjectParameter("vemail_cli", typeof(string));
    
            var ves_duenoParameter = ves_dueno.HasValue ?
                new ObjectParameter("ves_dueno", ves_dueno) :
                new ObjectParameter("ves_dueno", typeof(int));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vdni_cliParameter = vdni_cli != null ?
                new ObjectParameter("vdni_cli", vdni_cli) :
                new ObjectParameter("vdni_cli", typeof(string));
    
            var vusu_ult_modParameter = vusu_ult_mod != null ?
                new ObjectParameter("vusu_ult_mod", vusu_ult_mod) :
                new ObjectParameter("vusu_ult_mod", typeof(string));
    
            var vestado_cliParameter = vestado_cli.HasValue ?
                new ObjectParameter("vestado_cli", vestado_cli) :
                new ObjectParameter("vestado_cli", typeof(int));
    
            var vcod_cliParameter = vcod_cli != null ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCliente", vnom_clienteParameter, vape_cliParameter, vdir_cliParameter, vcel_cliParameter, vemail_cliParameter, ves_duenoParameter, vid_ubigeoParameter, vdni_cliParameter, vusu_ult_modParameter, vestado_cliParameter, vcod_cliParameter);
        }
    
        public virtual int usp_ActualizarEmpleado(Nullable<int> vcod_rol, Nullable<int> vtipo_emp, string vnom_emp, string vape_emp, string vdir_emp, string vid_ubigeo, Nullable<System.DateTime> vfecha_ingreso, Nullable<decimal> vsueldo, string vemail_emp, string vcod_sup, string vusu_ult_mod, Nullable<int> vestado_emp, string vcod_emp)
        {
            var vcod_rolParameter = vcod_rol.HasValue ?
                new ObjectParameter("vcod_rol", vcod_rol) :
                new ObjectParameter("vcod_rol", typeof(int));
    
            var vtipo_empParameter = vtipo_emp.HasValue ?
                new ObjectParameter("vtipo_emp", vtipo_emp) :
                new ObjectParameter("vtipo_emp", typeof(int));
    
            var vnom_empParameter = vnom_emp != null ?
                new ObjectParameter("vnom_emp", vnom_emp) :
                new ObjectParameter("vnom_emp", typeof(string));
    
            var vape_empParameter = vape_emp != null ?
                new ObjectParameter("vape_emp", vape_emp) :
                new ObjectParameter("vape_emp", typeof(string));
    
            var vdir_empParameter = vdir_emp != null ?
                new ObjectParameter("vdir_emp", vdir_emp) :
                new ObjectParameter("vdir_emp", typeof(string));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vfecha_ingresoParameter = vfecha_ingreso.HasValue ?
                new ObjectParameter("vfecha_ingreso", vfecha_ingreso) :
                new ObjectParameter("vfecha_ingreso", typeof(System.DateTime));
    
            var vsueldoParameter = vsueldo.HasValue ?
                new ObjectParameter("vsueldo", vsueldo) :
                new ObjectParameter("vsueldo", typeof(decimal));
    
            var vemail_empParameter = vemail_emp != null ?
                new ObjectParameter("vemail_emp", vemail_emp) :
                new ObjectParameter("vemail_emp", typeof(string));
    
            var vcod_supParameter = vcod_sup != null ?
                new ObjectParameter("vcod_sup", vcod_sup) :
                new ObjectParameter("vcod_sup", typeof(string));
    
            var vusu_ult_modParameter = vusu_ult_mod != null ?
                new ObjectParameter("vusu_ult_mod", vusu_ult_mod) :
                new ObjectParameter("vusu_ult_mod", typeof(string));
    
            var vestado_empParameter = vestado_emp.HasValue ?
                new ObjectParameter("vestado_emp", vestado_emp) :
                new ObjectParameter("vestado_emp", typeof(int));
    
            var vcod_empParameter = vcod_emp != null ?
                new ObjectParameter("vcod_emp", vcod_emp) :
                new ObjectParameter("vcod_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEmpleado", vcod_rolParameter, vtipo_empParameter, vnom_empParameter, vape_empParameter, vdir_empParameter, vid_ubigeoParameter, vfecha_ingresoParameter, vsueldoParameter, vemail_empParameter, vcod_supParameter, vusu_ult_modParameter, vestado_empParameter, vcod_empParameter);
        }
    
        public virtual int usp_ActualizarPaciente(string vnom_pac, Nullable<int> vcod_raza, Nullable<System.DateTime> vfec_nac_pac, Nullable<int> vsexo, Nullable<int> vcod_color, Nullable<double> vlongitud, Nullable<double> vpeso, byte[] vfoto, string vobservaciones_pac, Nullable<int> vest_pac, string vcod_pac)
        {
            var vnom_pacParameter = vnom_pac != null ?
                new ObjectParameter("vnom_pac", vnom_pac) :
                new ObjectParameter("vnom_pac", typeof(string));
    
            var vcod_razaParameter = vcod_raza.HasValue ?
                new ObjectParameter("vcod_raza", vcod_raza) :
                new ObjectParameter("vcod_raza", typeof(int));
    
            var vfec_nac_pacParameter = vfec_nac_pac.HasValue ?
                new ObjectParameter("vfec_nac_pac", vfec_nac_pac) :
                new ObjectParameter("vfec_nac_pac", typeof(System.DateTime));
    
            var vsexoParameter = vsexo.HasValue ?
                new ObjectParameter("vsexo", vsexo) :
                new ObjectParameter("vsexo", typeof(int));
    
            var vcod_colorParameter = vcod_color.HasValue ?
                new ObjectParameter("vcod_color", vcod_color) :
                new ObjectParameter("vcod_color", typeof(int));
    
            var vlongitudParameter = vlongitud.HasValue ?
                new ObjectParameter("vlongitud", vlongitud) :
                new ObjectParameter("vlongitud", typeof(double));
    
            var vpesoParameter = vpeso.HasValue ?
                new ObjectParameter("vpeso", vpeso) :
                new ObjectParameter("vpeso", typeof(double));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vobservaciones_pacParameter = vobservaciones_pac != null ?
                new ObjectParameter("vobservaciones_pac", vobservaciones_pac) :
                new ObjectParameter("vobservaciones_pac", typeof(string));
    
            var vest_pacParameter = vest_pac.HasValue ?
                new ObjectParameter("vest_pac", vest_pac) :
                new ObjectParameter("vest_pac", typeof(int));
    
            var vcod_pacParameter = vcod_pac != null ?
                new ObjectParameter("vcod_pac", vcod_pac) :
                new ObjectParameter("vcod_pac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarPaciente", vnom_pacParameter, vcod_razaParameter, vfec_nac_pacParameter, vsexoParameter, vcod_colorParameter, vlongitudParameter, vpesoParameter, vfotoParameter, vobservaciones_pacParameter, vest_pacParameter, vcod_pacParameter);
        }
    
        public virtual int usp_ActualizarReservarCita(Nullable<System.DateTime> vfec_cita, Nullable<System.TimeSpan> vhor_cita, string vcod_cli, Nullable<int> vcod_cita)
        {
            var vfec_citaParameter = vfec_cita.HasValue ?
                new ObjectParameter("vfec_cita", vfec_cita) :
                new ObjectParameter("vfec_cita", typeof(System.DateTime));
    
            var vhor_citaParameter = vhor_cita.HasValue ?
                new ObjectParameter("vhor_cita", vhor_cita) :
                new ObjectParameter("vhor_cita", typeof(System.TimeSpan));
    
            var vcod_cliParameter = vcod_cli != null ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(string));
    
            var vcod_citaParameter = vcod_cita.HasValue ?
                new ObjectParameter("vcod_cita", vcod_cita) :
                new ObjectParameter("vcod_cita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarReservarCita", vfec_citaParameter, vhor_citaParameter, vcod_cliParameter, vcod_citaParameter);
        }
    
        public virtual int usp_AgregarDetallesDeConsulta(Nullable<int> vcod_cons, Nullable<int> vcod_trat, Nullable<int> vcod_estado, Nullable<int> vcod_med, string vobs_det_cons)
        {
            var vcod_consParameter = vcod_cons.HasValue ?
                new ObjectParameter("vcod_cons", vcod_cons) :
                new ObjectParameter("vcod_cons", typeof(int));
    
            var vcod_tratParameter = vcod_trat.HasValue ?
                new ObjectParameter("vcod_trat", vcod_trat) :
                new ObjectParameter("vcod_trat", typeof(int));
    
            var vcod_estadoParameter = vcod_estado.HasValue ?
                new ObjectParameter("vcod_estado", vcod_estado) :
                new ObjectParameter("vcod_estado", typeof(int));
    
            var vcod_medParameter = vcod_med.HasValue ?
                new ObjectParameter("vcod_med", vcod_med) :
                new ObjectParameter("vcod_med", typeof(int));
    
            var vobs_det_consParameter = vobs_det_cons != null ?
                new ObjectParameter("vobs_det_cons", vobs_det_cons) :
                new ObjectParameter("vobs_det_cons", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AgregarDetallesDeConsulta", vcod_consParameter, vcod_tratParameter, vcod_estadoParameter, vcod_medParameter, vobs_det_consParameter);
        }
    
        public virtual int usp_CancelarConsulta(Nullable<int> vcod_cons)
        {
            var vcod_consParameter = vcod_cons.HasValue ?
                new ObjectParameter("vcod_cons", vcod_cons) :
                new ObjectParameter("vcod_cons", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CancelarConsulta", vcod_consParameter);
        }
    
        public virtual int usp_CancelarReserva(Nullable<int> vcod_cita)
        {
            var vcod_citaParameter = vcod_cita.HasValue ?
                new ObjectParameter("vcod_cita", vcod_cita) :
                new ObjectParameter("vcod_cita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CancelarReserva", vcod_citaParameter);
        }
    
        public virtual ObjectResult<usp_ConsultasEntreFechas_Result> usp_ConsultasEntreFechas(Nullable<System.DateTime> vfec_ini, Nullable<System.DateTime> vfec_fin)
        {
            var vfec_iniParameter = vfec_ini.HasValue ?
                new ObjectParameter("vfec_ini", vfec_ini) :
                new ObjectParameter("vfec_ini", typeof(System.DateTime));
    
            var vfec_finParameter = vfec_fin.HasValue ?
                new ObjectParameter("vfec_fin", vfec_fin) :
                new ObjectParameter("vfec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultasEntreFechas_Result>("usp_ConsultasEntreFechas", vfec_iniParameter, vfec_finParameter);
        }
    
        public virtual ObjectResult<usp_ConsultasPorFecha_Result> usp_ConsultasPorFecha(Nullable<System.DateTime> vfec_con)
        {
            var vfec_conParameter = vfec_con.HasValue ?
                new ObjectParameter("vfec_con", vfec_con) :
                new ObjectParameter("vfec_con", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultasPorFecha_Result>("usp_ConsultasPorFecha", vfec_conParameter);
        }
    
        public virtual ObjectResult<usp_ConsultasPorMascota_Result> usp_ConsultasPorMascota(string vcod_pac)
        {
            var vcod_pacParameter = vcod_pac != null ?
                new ObjectParameter("vcod_pac", vcod_pac) :
                new ObjectParameter("vcod_pac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultasPorMascota_Result>("usp_ConsultasPorMascota", vcod_pacParameter);
        }
    
        public virtual ObjectResult<usp_ConsultasPorMascotaEntreFechas_Result> usp_ConsultasPorMascotaEntreFechas(string vcod_pac, Nullable<System.DateTime> vfec_ini, Nullable<System.DateTime> vfec_fin)
        {
            var vcod_pacParameter = vcod_pac != null ?
                new ObjectParameter("vcod_pac", vcod_pac) :
                new ObjectParameter("vcod_pac", typeof(string));
    
            var vfec_iniParameter = vfec_ini.HasValue ?
                new ObjectParameter("vfec_ini", vfec_ini) :
                new ObjectParameter("vfec_ini", typeof(System.DateTime));
    
            var vfec_finParameter = vfec_fin.HasValue ?
                new ObjectParameter("vfec_fin", vfec_fin) :
                new ObjectParameter("vfec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultasPorMascotaEntreFechas_Result>("usp_ConsultasPorMascotaEntreFechas", vcod_pacParameter, vfec_iniParameter, vfec_finParameter);
        }
    
        public virtual ObjectResult<usp_ConsultasPorMedico_Result> usp_ConsultasPorMedico(string vcod_emp)
        {
            var vcod_empParameter = vcod_emp != null ?
                new ObjectParameter("vcod_emp", vcod_emp) :
                new ObjectParameter("vcod_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultasPorMedico_Result>("usp_ConsultasPorMedico", vcod_empParameter);
        }
    
        public virtual ObjectResult<usp_ConsultasPorMedicoEntreFechas_Result> usp_ConsultasPorMedicoEntreFechas(string vcod_emp, Nullable<System.DateTime> vfec_ini, Nullable<System.DateTime> vfec_fin)
        {
            var vcod_empParameter = vcod_emp != null ?
                new ObjectParameter("vcod_emp", vcod_emp) :
                new ObjectParameter("vcod_emp", typeof(string));
    
            var vfec_iniParameter = vfec_ini.HasValue ?
                new ObjectParameter("vfec_ini", vfec_ini) :
                new ObjectParameter("vfec_ini", typeof(System.DateTime));
    
            var vfec_finParameter = vfec_fin.HasValue ?
                new ObjectParameter("vfec_fin", vfec_fin) :
                new ObjectParameter("vfec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultasPorMedicoEntreFechas_Result>("usp_ConsultasPorMedicoEntreFechas", vcod_empParameter, vfec_iniParameter, vfec_finParameter);
        }
    
        public virtual int usp_EliminarCliente(string vcod_cli)
        {
            var vcod_cliParameter = vcod_cli != null ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCliente", vcod_cliParameter);
        }
    
        public virtual int usp_EliminarEmpleado(string vcod_emp)
        {
            var vcod_empParameter = vcod_emp != null ?
                new ObjectParameter("vcod_emp", vcod_emp) :
                new ObjectParameter("vcod_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEmpleado", vcod_empParameter);
        }
    
        public virtual ObjectResult<usp_EmpleadosPorDepartamento_Result> usp_EmpleadosPorDepartamento(string vdep)
        {
            var vdepParameter = vdep != null ?
                new ObjectParameter("vdep", vdep) :
                new ObjectParameter("vdep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_EmpleadosPorDepartamento_Result>("usp_EmpleadosPorDepartamento", vdepParameter);
        }
    
        public virtual int usp_GenerarConsulta(string vcod_pac, string vcod_emp, Nullable<int> vcod_cita)
        {
            var vcod_pacParameter = vcod_pac != null ?
                new ObjectParameter("vcod_pac", vcod_pac) :
                new ObjectParameter("vcod_pac", typeof(string));
    
            var vcod_empParameter = vcod_emp != null ?
                new ObjectParameter("vcod_emp", vcod_emp) :
                new ObjectParameter("vcod_emp", typeof(string));
    
            var vcod_citaParameter = vcod_cita.HasValue ?
                new ObjectParameter("vcod_cita", vcod_cita) :
                new ObjectParameter("vcod_cita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GenerarConsulta", vcod_pacParameter, vcod_empParameter, vcod_citaParameter);
        }
    
        public virtual int usp_InsertarCliente(string vnom_cliente, string vape_cli, string vdir_cli, string vcel_cli, string vemail_cli, Nullable<int> ves_dueno, string vid_ubigeo, string vdni_cli, string vusu_reg_cli, Nullable<int> vestado_cli)
        {
            var vnom_clienteParameter = vnom_cliente != null ?
                new ObjectParameter("vnom_cliente", vnom_cliente) :
                new ObjectParameter("vnom_cliente", typeof(string));
    
            var vape_cliParameter = vape_cli != null ?
                new ObjectParameter("vape_cli", vape_cli) :
                new ObjectParameter("vape_cli", typeof(string));
    
            var vdir_cliParameter = vdir_cli != null ?
                new ObjectParameter("vdir_cli", vdir_cli) :
                new ObjectParameter("vdir_cli", typeof(string));
    
            var vcel_cliParameter = vcel_cli != null ?
                new ObjectParameter("vcel_cli", vcel_cli) :
                new ObjectParameter("vcel_cli", typeof(string));
    
            var vemail_cliParameter = vemail_cli != null ?
                new ObjectParameter("vemail_cli", vemail_cli) :
                new ObjectParameter("vemail_cli", typeof(string));
    
            var ves_duenoParameter = ves_dueno.HasValue ?
                new ObjectParameter("ves_dueno", ves_dueno) :
                new ObjectParameter("ves_dueno", typeof(int));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vdni_cliParameter = vdni_cli != null ?
                new ObjectParameter("vdni_cli", vdni_cli) :
                new ObjectParameter("vdni_cli", typeof(string));
    
            var vusu_reg_cliParameter = vusu_reg_cli != null ?
                new ObjectParameter("vusu_reg_cli", vusu_reg_cli) :
                new ObjectParameter("vusu_reg_cli", typeof(string));
    
            var vestado_cliParameter = vestado_cli.HasValue ?
                new ObjectParameter("vestado_cli", vestado_cli) :
                new ObjectParameter("vestado_cli", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", vnom_clienteParameter, vape_cliParameter, vdir_cliParameter, vcel_cliParameter, vemail_cliParameter, ves_duenoParameter, vid_ubigeoParameter, vdni_cliParameter, vusu_reg_cliParameter, vestado_cliParameter);
        }
    
        public virtual int usp_InsertarEmpleado(Nullable<int> vcod_rol, Nullable<int> vtipo_emp, string vnom_emp, string vape_emp, string vdir_emp, string vid_ubigeo, Nullable<System.DateTime> vfecha_ingreso, Nullable<decimal> vsueldo, string vemail_emp, string vcod_sup, string vusu_reg, Nullable<int> vestado_emp)
        {
            var vcod_rolParameter = vcod_rol.HasValue ?
                new ObjectParameter("vcod_rol", vcod_rol) :
                new ObjectParameter("vcod_rol", typeof(int));
    
            var vtipo_empParameter = vtipo_emp.HasValue ?
                new ObjectParameter("vtipo_emp", vtipo_emp) :
                new ObjectParameter("vtipo_emp", typeof(int));
    
            var vnom_empParameter = vnom_emp != null ?
                new ObjectParameter("vnom_emp", vnom_emp) :
                new ObjectParameter("vnom_emp", typeof(string));
    
            var vape_empParameter = vape_emp != null ?
                new ObjectParameter("vape_emp", vape_emp) :
                new ObjectParameter("vape_emp", typeof(string));
    
            var vdir_empParameter = vdir_emp != null ?
                new ObjectParameter("vdir_emp", vdir_emp) :
                new ObjectParameter("vdir_emp", typeof(string));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vfecha_ingresoParameter = vfecha_ingreso.HasValue ?
                new ObjectParameter("vfecha_ingreso", vfecha_ingreso) :
                new ObjectParameter("vfecha_ingreso", typeof(System.DateTime));
    
            var vsueldoParameter = vsueldo.HasValue ?
                new ObjectParameter("vsueldo", vsueldo) :
                new ObjectParameter("vsueldo", typeof(decimal));
    
            var vemail_empParameter = vemail_emp != null ?
                new ObjectParameter("vemail_emp", vemail_emp) :
                new ObjectParameter("vemail_emp", typeof(string));
    
            var vcod_supParameter = vcod_sup != null ?
                new ObjectParameter("vcod_sup", vcod_sup) :
                new ObjectParameter("vcod_sup", typeof(string));
    
            var vusu_regParameter = vusu_reg != null ?
                new ObjectParameter("vusu_reg", vusu_reg) :
                new ObjectParameter("vusu_reg", typeof(string));
    
            var vestado_empParameter = vestado_emp.HasValue ?
                new ObjectParameter("vestado_emp", vestado_emp) :
                new ObjectParameter("vestado_emp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEmpleado", vcod_rolParameter, vtipo_empParameter, vnom_empParameter, vape_empParameter, vdir_empParameter, vid_ubigeoParameter, vfecha_ingresoParameter, vsueldoParameter, vemail_empParameter, vcod_supParameter, vusu_regParameter, vestado_empParameter);
        }
    
        public virtual int usp_InsertarPaciente(string vnom_pac, Nullable<int> vcod_raza, Nullable<System.DateTime> vfec_nac_pac, Nullable<int> vsexo, Nullable<int> vcod_color, Nullable<double> vlongitud, Nullable<double> vpeso, Nullable<System.DateTime> vult_vis_pac, byte[] vfoto, string vobservaciones_pac, Nullable<int> vest_pac)
        {
            var vnom_pacParameter = vnom_pac != null ?
                new ObjectParameter("vnom_pac", vnom_pac) :
                new ObjectParameter("vnom_pac", typeof(string));
    
            var vcod_razaParameter = vcod_raza.HasValue ?
                new ObjectParameter("vcod_raza", vcod_raza) :
                new ObjectParameter("vcod_raza", typeof(int));
    
            var vfec_nac_pacParameter = vfec_nac_pac.HasValue ?
                new ObjectParameter("vfec_nac_pac", vfec_nac_pac) :
                new ObjectParameter("vfec_nac_pac", typeof(System.DateTime));
    
            var vsexoParameter = vsexo.HasValue ?
                new ObjectParameter("vsexo", vsexo) :
                new ObjectParameter("vsexo", typeof(int));
    
            var vcod_colorParameter = vcod_color.HasValue ?
                new ObjectParameter("vcod_color", vcod_color) :
                new ObjectParameter("vcod_color", typeof(int));
    
            var vlongitudParameter = vlongitud.HasValue ?
                new ObjectParameter("vlongitud", vlongitud) :
                new ObjectParameter("vlongitud", typeof(double));
    
            var vpesoParameter = vpeso.HasValue ?
                new ObjectParameter("vpeso", vpeso) :
                new ObjectParameter("vpeso", typeof(double));
    
            var vult_vis_pacParameter = vult_vis_pac.HasValue ?
                new ObjectParameter("vult_vis_pac", vult_vis_pac) :
                new ObjectParameter("vult_vis_pac", typeof(System.DateTime));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vobservaciones_pacParameter = vobservaciones_pac != null ?
                new ObjectParameter("vobservaciones_pac", vobservaciones_pac) :
                new ObjectParameter("vobservaciones_pac", typeof(string));
    
            var vest_pacParameter = vest_pac.HasValue ?
                new ObjectParameter("vest_pac", vest_pac) :
                new ObjectParameter("vest_pac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarPaciente", vnom_pacParameter, vcod_razaParameter, vfec_nac_pacParameter, vsexoParameter, vcod_colorParameter, vlongitudParameter, vpesoParameter, vult_vis_pacParameter, vfotoParameter, vobservaciones_pacParameter, vest_pacParameter);
        }
    
        public virtual ObjectResult<usp_ListarClientes_Result> usp_ListarClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarClientes_Result>("usp_ListarClientes");
        }
    
        public virtual ObjectResult<usp_ListarEmpleado_Result> usp_ListarEmpleado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEmpleado_Result>("usp_ListarEmpleado");
        }
    
        public virtual ObjectResult<usp_ListarMedicinasPorProveedor_Result> usp_ListarMedicinasPorProveedor(string vcod_prov)
        {
            var vcod_provParameter = vcod_prov != null ?
                new ObjectParameter("vcod_prov", vcod_prov) :
                new ObjectParameter("vcod_prov", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMedicinasPorProveedor_Result>("usp_ListarMedicinasPorProveedor", vcod_provParameter);
        }
    
        public virtual ObjectResult<usp_ListarPacientePorTratamiento_Result> usp_ListarPacientePorTratamiento(Nullable<int> vcod_trat)
        {
            var vcod_tratParameter = vcod_trat.HasValue ?
                new ObjectParameter("vcod_trat", vcod_trat) :
                new ObjectParameter("vcod_trat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPacientePorTratamiento_Result>("usp_ListarPacientePorTratamiento", vcod_tratParameter);
        }
    
        public virtual ObjectResult<usp_PacientesPorRaza_Result> usp_PacientesPorRaza(Nullable<int> vcod_raza)
        {
            var vcod_razaParameter = vcod_raza.HasValue ?
                new ObjectParameter("vcod_raza", vcod_raza) :
                new ObjectParameter("vcod_raza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PacientesPorRaza_Result>("usp_PacientesPorRaza", vcod_razaParameter);
        }
    
        public virtual int usp_ReservarCita(Nullable<System.DateTime> vfec_cita, Nullable<System.TimeSpan> vhor_cita, string vcod_cli)
        {
            var vfec_citaParameter = vfec_cita.HasValue ?
                new ObjectParameter("vfec_cita", vfec_cita) :
                new ObjectParameter("vfec_cita", typeof(System.DateTime));
    
            var vhor_citaParameter = vhor_cita.HasValue ?
                new ObjectParameter("vhor_cita", vhor_cita) :
                new ObjectParameter("vhor_cita", typeof(System.TimeSpan));
    
            var vcod_cliParameter = vcod_cli != null ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ReservarCita", vfec_citaParameter, vhor_citaParameter, vcod_cliParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_DistritosProvinciaDepartamento_Result> usp_Ubigeo_DistritosProvinciaDepartamento(string idDepa, string idProv)
        {
            var idDepaParameter = idDepa != null ?
                new ObjectParameter("IdDepa", idDepa) :
                new ObjectParameter("IdDepa", typeof(string));
    
            var idProvParameter = idProv != null ?
                new ObjectParameter("IdProv", idProv) :
                new ObjectParameter("IdProv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_DistritosProvinciaDepartamento_Result>("usp_Ubigeo_DistritosProvinciaDepartamento", idDepaParameter, idProvParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_ProvinciasDepartamento_Result> usp_Ubigeo_ProvinciasDepartamento(string idDepa)
        {
            var idDepaParameter = idDepa != null ?
                new ObjectParameter("IdDepa", idDepa) :
                new ObjectParameter("IdDepa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_ProvinciasDepartamento_Result>("usp_Ubigeo_ProvinciasDepartamento", idDepaParameter);
        }
    
        public virtual ObjectResult<usp_UbigeoDepartamentos_Result> usp_UbigeoDepartamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UbigeoDepartamentos_Result>("usp_UbigeoDepartamentos");
        }
    }
}
