//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hunde
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cliente()
        {
            this.Tb_Empleado = new HashSet<Tb_Empleado>();
        }
    
        public string cod_cli { get; set; }
        public int Tipo_ciente { get; set; }
        public string nom_cliente { get; set; }
        public string ape_pat_cliente { get; set; }
        public string ape_mat_cliente { get; set; }
        public string direccion_cliente { get; set; }
        public string cel_cliente { get; set; }
        public string email_cliente { get; set; }
        public int es_dueno { get; set; }
        public int es_empleado { get; set; }
        public string id_ubigeo { get; set; }
        public string dni_cliente { get; set; }
        public string usu_reg_cli { get; set; }
        public Nullable<System.DateTime> fec_reg_cli { get; set; }
        public string usu_ult_modificacion_cli { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion_cli { get; set; }
        public Nullable<int> estado_cli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Empleado> Tb_Empleado { get; set; }
    }
}
