//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hunde
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Empleado()
        {
            this.Tb_Usuario = new HashSet<Tb_Usuario>();
        }
    
        public string cod_emp { get; set; }
        public int rol_emp { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public string email_emp { get; set; }
        public string cod_supervisor { get; set; }
        public string cod_cli { get; set; }
        public string usu_ult_modificacion_emp { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion_emp { get; set; }
        public int estado_emp { get; set; }
    
        public virtual Tb_Cliente Tb_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Usuario> Tb_Usuario { get; set; }
    }
}
