//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hunde
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Empleado()
        {
            this.Tb_Empleado1 = new HashSet<Tb_Empleado>();
            this.Tb_Usuario = new HashSet<Tb_Usuario>();
            this.Tb_Consulta = new HashSet<Tb_Consulta>();
        }
    
        public string cod_emp { get; set; }
        public int cod_rol { get; set; }
        public int tipo_emp { get; set; }
        public string nom_empleado { get; set; }
        public string ape_empleado { get; set; }
        public string direccion_empleado { get; set; }
        public string id_ubigeo { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public string email_emp { get; set; }
        public string cod_supervisor { get; set; }
        public string usu_reg_cli { get; set; }
        public Nullable<System.DateTime> fec_reg_cli { get; set; }
        public string usu_ult_modificacion_emp { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion_emp { get; set; }
        public int estado_emp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Empleado> Tb_Empleado1 { get; set; }
        public virtual Tb_Empleado Tb_Empleado2 { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        public virtual Tb_Rol Tb_Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Usuario> Tb_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Consulta> Tb_Consulta { get; set; }
    }
}
