//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hunde
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Proveedor
    {
        public string cod_prov { get; set; }
        public string nom_prov { get; set; }
        public string ruc_prov { get; set; }
        public string direccion_prov { get; set; }
        public string tel_prov { get; set; }
        public string email_prov { get; set; }
        public string rep_ven_prov { get; set; }
        public string usu_reg_prov { get; set; }
        public Nullable<System.DateTime> fec_reg_prov { get; set; }
        public string usu_ult_modificacion_prov { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion_prov { get; set; }
        public Nullable<int> estado_prov { get; set; }
    }
}
