//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hunde
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientesSonEmpleados
    {
        public string cod_emp { get; set; }
        public int rol_emp { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public string email_emp { get; set; }
        public string cod_supervisor { get; set; }
        public string cod_cli { get; set; }
        public string usu_ult_modificacion_emp { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion_emp { get; set; }
        public int estado_emp { get; set; }
        public int tipo_ciente { get; set; }
        public string nom_cliente { get; set; }
        public string ape_pat_cliente { get; set; }
        public string ape_mat_cliente { get; set; }
        public string direccion_cliente { get; set; }
        public string cel_cliente { get; set; }
        public string email_cliente { get; set; }
        public int es_dueno { get; set; }
        public int es_empleado { get; set; }
        public string id_ubigeo { get; set; }
        public string dni_cliente { get; set; }
        public string usu_reg_cli { get; set; }
        public Nullable<System.DateTime> fec_reg_cli { get; set; }
        public string usu_ult_modificacion_cli { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion_cli { get; set; }
        public Nullable<int> estado_cli { get; set; }
    }
}
