//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hunde
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Consultas
    {
        public int cod_cita { get; set; }
        public int cod_cons { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string cod_emp { get; set; }
        public string medico { get; set; }
        public string cod_pac { get; set; }
        public string mascota { get; set; }
        public string tipo { get; set; }
        public string raza { get; set; }
        public string color { get; set; }
        public string cod_cli { get; set; }
        public string lo_trajo { get; set; }
        public int est_cons { get; set; }
        public string conducta { get; set; }
        public string est_nutricional { get; set; }
        public string actividad { get; set; }
        public string observaciones { get; set; }
    }
}
