//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hunde
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DetallesPaciente
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string tipo_paciente { get; set; }
        public string raza { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public int sexo { get; set; }
        public string color { get; set; }
        public double longitud { get; set; }
        public double peso { get; set; }
        public string conducta { get; set; }
        public string nutricion { get; set; }
        public string actividad { get; set; }
        public string observaciones { get; set; }
        public string detalles_observaciones { get; set; }
        public int estado { get; set; }
    }
}
