//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string login_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short niv_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usu_reg_usuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_emp {
            get {
                return this.cod_empField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_empField, value) != true)) {
                    this.cod_empField = value;
                    this.RaisePropertyChanged("cod_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_usuario {
            get {
                return this.est_usuarioField;
            }
            set {
                if ((this.est_usuarioField.Equals(value) != true)) {
                    this.est_usuarioField = value;
                    this.RaisePropertyChanged("est_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_registro {
            get {
                return this.fec_registroField;
            }
            set {
                if ((this.fec_registroField.Equals(value) != true)) {
                    this.fec_registroField = value;
                    this.RaisePropertyChanged("fec_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login_usuario {
            get {
                return this.login_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.login_usuarioField, value) != true)) {
                    this.login_usuarioField = value;
                    this.RaisePropertyChanged("login_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short niv_usuario {
            get {
                return this.niv_usuarioField;
            }
            set {
                if ((this.niv_usuarioField.Equals(value) != true)) {
                    this.niv_usuarioField = value;
                    this.RaisePropertyChanged("niv_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass_usuario {
            get {
                return this.pass_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.pass_usuarioField, value) != true)) {
                    this.pass_usuarioField = value;
                    this.RaisePropertyChanged("pass_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usu_reg_usu {
            get {
                return this.usu_reg_usuField;
            }
            set {
                if ((object.ReferenceEquals(this.usu_reg_usuField, value) != true)) {
                    this.usu_reg_usuField = value;
                    this.RaisePropertyChanged("usu_reg_usu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuario.IServicioUsuario")]
    public interface IServicioUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/ConsultarUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/ConsultarUsuarioResponse")]
        Win_Hunde.ProxyUsuario.Usuario ConsultarUsuario(string strLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/ConsultarUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/ConsultarUsuarioResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyUsuario.Usuario> ConsultarUsuarioAsync(string strLogin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioChannel : Win_Hunde.ProxyUsuario.IServicioUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyUsuario.IServicioUsuario>, Win_Hunde.ProxyUsuario.IServicioUsuario {
        
        public ServicioUsuarioClient() {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Win_Hunde.ProxyUsuario.Usuario ConsultarUsuario(string strLogin) {
            return base.Channel.ConsultarUsuario(strLogin);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyUsuario.Usuario> ConsultarUsuarioAsync(string strLogin) {
            return base.Channel.ConsultarUsuarioAsync(strLogin);
        }
    }
}
