//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_HundeCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HundeDBEntities : DbContext
    {
        public HundeDBEntities()
            : base("name=HundeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Cita> Tb_Cita { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_Color> Tb_Color { get; set; }
        public virtual DbSet<Tb_Empleado> Tb_Empleado { get; set; }
        public virtual DbSet<Tb_Medicina> Tb_Medicina { get; set; }
        public virtual DbSet<Tb_Paciente> Tb_Paciente { get; set; }
        public virtual DbSet<Tb_Proveedor> Tb_Proveedor { get; set; }
        public virtual DbSet<Tb_Raza> Tb_Raza { get; set; }
        public virtual DbSet<Tb_Tratamiento> Tb_Tratamiento { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<vw_ClientesPacientes> vw_ClientesPacientes { get; set; }
        public virtual DbSet<vw_ClientesSonDueños> vw_ClientesSonDueños { get; set; }
        public virtual DbSet<vw_DetallesPaciente> vw_DetallesPaciente { get; set; }
    
        public virtual int usp_ActualizarCliente(string vnom_cliente, string vape_cli, string vdir_cli, string vcel_cli, string vemail_cli, Nullable<int> ves_dueno, string vid_ubigeo, string vdni_cli, string vusu_ult_mod, Nullable<int> vestado_cli, string vcod_cli)
        {
            var vnom_clienteParameter = vnom_cliente != null ?
                new ObjectParameter("vnom_cliente", vnom_cliente) :
                new ObjectParameter("vnom_cliente", typeof(string));
    
            var vape_cliParameter = vape_cli != null ?
                new ObjectParameter("vape_cli", vape_cli) :
                new ObjectParameter("vape_cli", typeof(string));
    
            var vdir_cliParameter = vdir_cli != null ?
                new ObjectParameter("vdir_cli", vdir_cli) :
                new ObjectParameter("vdir_cli", typeof(string));
    
            var vcel_cliParameter = vcel_cli != null ?
                new ObjectParameter("vcel_cli", vcel_cli) :
                new ObjectParameter("vcel_cli", typeof(string));
    
            var vemail_cliParameter = vemail_cli != null ?
                new ObjectParameter("vemail_cli", vemail_cli) :
                new ObjectParameter("vemail_cli", typeof(string));
    
            var ves_duenoParameter = ves_dueno.HasValue ?
                new ObjectParameter("ves_dueno", ves_dueno) :
                new ObjectParameter("ves_dueno", typeof(int));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vdni_cliParameter = vdni_cli != null ?
                new ObjectParameter("vdni_cli", vdni_cli) :
                new ObjectParameter("vdni_cli", typeof(string));
    
            var vusu_ult_modParameter = vusu_ult_mod != null ?
                new ObjectParameter("vusu_ult_mod", vusu_ult_mod) :
                new ObjectParameter("vusu_ult_mod", typeof(string));
    
            var vestado_cliParameter = vestado_cli.HasValue ?
                new ObjectParameter("vestado_cli", vestado_cli) :
                new ObjectParameter("vestado_cli", typeof(int));
    
            var vcod_cliParameter = vcod_cli != null ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCliente", vnom_clienteParameter, vape_cliParameter, vdir_cliParameter, vcel_cliParameter, vemail_cliParameter, ves_duenoParameter, vid_ubigeoParameter, vdni_cliParameter, vusu_ult_modParameter, vestado_cliParameter, vcod_cliParameter);
        }
    
        public virtual int usp_EliminarCliente(string vcod_cli)
        {
            var vcod_cliParameter = vcod_cli != null ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCliente", vcod_cliParameter);
        }
    
        public virtual int usp_InsertarCliente(string vnom_cliente, string vape_cli, string vdir_cli, string vcel_cli, string vemail_cli, Nullable<int> ves_dueno, string vid_ubigeo, string vdni_cli, string vusu_reg_cli, Nullable<int> vestado_cli)
        {
            var vnom_clienteParameter = vnom_cliente != null ?
                new ObjectParameter("vnom_cliente", vnom_cliente) :
                new ObjectParameter("vnom_cliente", typeof(string));
    
            var vape_cliParameter = vape_cli != null ?
                new ObjectParameter("vape_cli", vape_cli) :
                new ObjectParameter("vape_cli", typeof(string));
    
            var vdir_cliParameter = vdir_cli != null ?
                new ObjectParameter("vdir_cli", vdir_cli) :
                new ObjectParameter("vdir_cli", typeof(string));
    
            var vcel_cliParameter = vcel_cli != null ?
                new ObjectParameter("vcel_cli", vcel_cli) :
                new ObjectParameter("vcel_cli", typeof(string));
    
            var vemail_cliParameter = vemail_cli != null ?
                new ObjectParameter("vemail_cli", vemail_cli) :
                new ObjectParameter("vemail_cli", typeof(string));
    
            var ves_duenoParameter = ves_dueno.HasValue ?
                new ObjectParameter("ves_dueno", ves_dueno) :
                new ObjectParameter("ves_dueno", typeof(int));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vdni_cliParameter = vdni_cli != null ?
                new ObjectParameter("vdni_cli", vdni_cli) :
                new ObjectParameter("vdni_cli", typeof(string));
    
            var vusu_reg_cliParameter = vusu_reg_cli != null ?
                new ObjectParameter("vusu_reg_cli", vusu_reg_cli) :
                new ObjectParameter("vusu_reg_cli", typeof(string));
    
            var vestado_cliParameter = vestado_cli.HasValue ?
                new ObjectParameter("vestado_cli", vestado_cli) :
                new ObjectParameter("vestado_cli", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", vnom_clienteParameter, vape_cliParameter, vdir_cliParameter, vcel_cliParameter, vemail_cliParameter, ves_duenoParameter, vid_ubigeoParameter, vdni_cliParameter, vusu_reg_cliParameter, vestado_cliParameter);
        }
    }
}
