//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_HundeCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HundeDBEntities : DbContext
    {
        public HundeDBEntities()
            : base("name=HundeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Cita> Tb_Cita { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_Color> Tb_Color { get; set; }
        public virtual DbSet<Tb_Empleado> Tb_Empleado { get; set; }
        public virtual DbSet<Tb_Medicina> Tb_Medicina { get; set; }
        public virtual DbSet<Tb_Paciente> Tb_Paciente { get; set; }
        public virtual DbSet<Tb_Proveedor> Tb_Proveedor { get; set; }
        public virtual DbSet<Tb_Raza> Tb_Raza { get; set; }
        public virtual DbSet<Tb_Tratamiento> Tb_Tratamiento { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<vw_ClientesPacientes> vw_ClientesPacientes { get; set; }
        public virtual DbSet<vw_ClientesSonDueños> vw_ClientesSonDueños { get; set; }
        public virtual DbSet<vw_DetallesPaciente> vw_DetallesPaciente { get; set; }
    
        public virtual int usp_ActualizarCliente(string vnom_cliente, string vape_cli, string vdir_cli, string vcel_cli, string vemail_cli, Nullable<int> ves_dueno, string vid_ubigeo, string vdni_cli, string vusu_ult_mod, Nullable<int> vestado_cli, string vcod_cli)
        {
            var vnom_clienteParameter = vnom_cliente != null ?
                new ObjectParameter("vnom_cliente", vnom_cliente) :
                new ObjectParameter("vnom_cliente", typeof(string));
    
            var vape_cliParameter = vape_cli != null ?
                new ObjectParameter("vape_cli", vape_cli) :
                new ObjectParameter("vape_cli", typeof(string));
    
            var vdir_cliParameter = vdir_cli != null ?
                new ObjectParameter("vdir_cli", vdir_cli) :
                new ObjectParameter("vdir_cli", typeof(string));
    
            var vcel_cliParameter = vcel_cli != null ?
                new ObjectParameter("vcel_cli", vcel_cli) :
                new ObjectParameter("vcel_cli", typeof(string));
    
            var vemail_cliParameter = vemail_cli != null ?
                new ObjectParameter("vemail_cli", vemail_cli) :
                new ObjectParameter("vemail_cli", typeof(string));
    
            var ves_duenoParameter = ves_dueno.HasValue ?
                new ObjectParameter("ves_dueno", ves_dueno) :
                new ObjectParameter("ves_dueno", typeof(int));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vdni_cliParameter = vdni_cli != null ?
                new ObjectParameter("vdni_cli", vdni_cli) :
                new ObjectParameter("vdni_cli", typeof(string));
    
            var vusu_ult_modParameter = vusu_ult_mod != null ?
                new ObjectParameter("vusu_ult_mod", vusu_ult_mod) :
                new ObjectParameter("vusu_ult_mod", typeof(string));
    
            var vestado_cliParameter = vestado_cli.HasValue ?
                new ObjectParameter("vestado_cli", vestado_cli) :
                new ObjectParameter("vestado_cli", typeof(int));
    
            var vcod_cliParameter = vcod_cli != null ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCliente", vnom_clienteParameter, vape_cliParameter, vdir_cliParameter, vcel_cliParameter, vemail_cliParameter, ves_duenoParameter, vid_ubigeoParameter, vdni_cliParameter, vusu_ult_modParameter, vestado_cliParameter, vcod_cliParameter);
        }
    
        public virtual int usp_EliminarCliente(string vcod_cli)
        {
            var vcod_cliParameter = vcod_cli != null ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCliente", vcod_cliParameter);
        }
    
        public virtual int usp_InsertarCliente(string vnom_cliente, string vape_cli, string vdir_cli, string vcel_cli, string vemail_cli, Nullable<int> ves_dueno, string vid_ubigeo, string vdni_cli, string vusu_reg_cli, Nullable<int> vestado_cli)
        {
            var vnom_clienteParameter = vnom_cliente != null ?
                new ObjectParameter("vnom_cliente", vnom_cliente) :
                new ObjectParameter("vnom_cliente", typeof(string));
    
            var vape_cliParameter = vape_cli != null ?
                new ObjectParameter("vape_cli", vape_cli) :
                new ObjectParameter("vape_cli", typeof(string));
    
            var vdir_cliParameter = vdir_cli != null ?
                new ObjectParameter("vdir_cli", vdir_cli) :
                new ObjectParameter("vdir_cli", typeof(string));
    
            var vcel_cliParameter = vcel_cli != null ?
                new ObjectParameter("vcel_cli", vcel_cli) :
                new ObjectParameter("vcel_cli", typeof(string));
    
            var vemail_cliParameter = vemail_cli != null ?
                new ObjectParameter("vemail_cli", vemail_cli) :
                new ObjectParameter("vemail_cli", typeof(string));
    
            var ves_duenoParameter = ves_dueno.HasValue ?
                new ObjectParameter("ves_dueno", ves_dueno) :
                new ObjectParameter("ves_dueno", typeof(int));
    
            var vid_ubigeoParameter = vid_ubigeo != null ?
                new ObjectParameter("vid_ubigeo", vid_ubigeo) :
                new ObjectParameter("vid_ubigeo", typeof(string));
    
            var vdni_cliParameter = vdni_cli != null ?
                new ObjectParameter("vdni_cli", vdni_cli) :
                new ObjectParameter("vdni_cli", typeof(string));
    
            var vusu_reg_cliParameter = vusu_reg_cli != null ?
                new ObjectParameter("vusu_reg_cli", vusu_reg_cli) :
                new ObjectParameter("vusu_reg_cli", typeof(string));
    
            var vestado_cliParameter = vestado_cli.HasValue ?
                new ObjectParameter("vestado_cli", vestado_cli) :
                new ObjectParameter("vestado_cli", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", vnom_clienteParameter, vape_cliParameter, vdir_cliParameter, vcel_cliParameter, vemail_cliParameter, ves_duenoParameter, vid_ubigeoParameter, vdni_cliParameter, vusu_reg_cliParameter, vestado_cliParameter);
        }
    
        public virtual int usp_ActualizarPaciente(string vnom_pac, Nullable<int> vcod_raza, Nullable<System.DateTime> vfec_nac_pac, Nullable<int> vsexo, Nullable<int> vcod_color, Nullable<double> vlongitud, Nullable<double> vpeso, byte[] vfoto, string vobservaciones_pac, Nullable<int> vest_pac, string vcod_pac)
        {
            var vnom_pacParameter = vnom_pac != null ?
                new ObjectParameter("vnom_pac", vnom_pac) :
                new ObjectParameter("vnom_pac", typeof(string));
    
            var vcod_razaParameter = vcod_raza.HasValue ?
                new ObjectParameter("vcod_raza", vcod_raza) :
                new ObjectParameter("vcod_raza", typeof(int));
    
            var vfec_nac_pacParameter = vfec_nac_pac.HasValue ?
                new ObjectParameter("vfec_nac_pac", vfec_nac_pac) :
                new ObjectParameter("vfec_nac_pac", typeof(System.DateTime));
    
            var vsexoParameter = vsexo.HasValue ?
                new ObjectParameter("vsexo", vsexo) :
                new ObjectParameter("vsexo", typeof(int));
    
            var vcod_colorParameter = vcod_color.HasValue ?
                new ObjectParameter("vcod_color", vcod_color) :
                new ObjectParameter("vcod_color", typeof(int));
    
            var vlongitudParameter = vlongitud.HasValue ?
                new ObjectParameter("vlongitud", vlongitud) :
                new ObjectParameter("vlongitud", typeof(double));
    
            var vpesoParameter = vpeso.HasValue ?
                new ObjectParameter("vpeso", vpeso) :
                new ObjectParameter("vpeso", typeof(double));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vobservaciones_pacParameter = vobservaciones_pac != null ?
                new ObjectParameter("vobservaciones_pac", vobservaciones_pac) :
                new ObjectParameter("vobservaciones_pac", typeof(string));
    
            var vest_pacParameter = vest_pac.HasValue ?
                new ObjectParameter("vest_pac", vest_pac) :
                new ObjectParameter("vest_pac", typeof(int));
    
            var vcod_pacParameter = vcod_pac != null ?
                new ObjectParameter("vcod_pac", vcod_pac) :
                new ObjectParameter("vcod_pac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarPaciente", vnom_pacParameter, vcod_razaParameter, vfec_nac_pacParameter, vsexoParameter, vcod_colorParameter, vlongitudParameter, vpesoParameter, vfotoParameter, vobservaciones_pacParameter, vest_pacParameter, vcod_pacParameter);
        }
    
        public virtual int usp_EliminarPaciente(string vcod_pac)
        {
            var vcod_pacParameter = vcod_pac != null ?
                new ObjectParameter("vcod_pac", vcod_pac) :
                new ObjectParameter("vcod_pac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarPaciente", vcod_pacParameter);
        }
    
        public virtual int usp_InsertarPaciente(string vnom_pac, Nullable<int> vcod_raza, Nullable<System.DateTime> vfec_nac_pac, Nullable<int> vsexo, Nullable<int> vcod_color, Nullable<double> vlongitud, Nullable<double> vpeso, Nullable<System.DateTime> vult_vis_pac, byte[] vfoto, string vobservaciones_pac, Nullable<int> vest_pac)
        {
            var vnom_pacParameter = vnom_pac != null ?
                new ObjectParameter("vnom_pac", vnom_pac) :
                new ObjectParameter("vnom_pac", typeof(string));
    
            var vcod_razaParameter = vcod_raza.HasValue ?
                new ObjectParameter("vcod_raza", vcod_raza) :
                new ObjectParameter("vcod_raza", typeof(int));
    
            var vfec_nac_pacParameter = vfec_nac_pac.HasValue ?
                new ObjectParameter("vfec_nac_pac", vfec_nac_pac) :
                new ObjectParameter("vfec_nac_pac", typeof(System.DateTime));
    
            var vsexoParameter = vsexo.HasValue ?
                new ObjectParameter("vsexo", vsexo) :
                new ObjectParameter("vsexo", typeof(int));
    
            var vcod_colorParameter = vcod_color.HasValue ?
                new ObjectParameter("vcod_color", vcod_color) :
                new ObjectParameter("vcod_color", typeof(int));
    
            var vlongitudParameter = vlongitud.HasValue ?
                new ObjectParameter("vlongitud", vlongitud) :
                new ObjectParameter("vlongitud", typeof(double));
    
            var vpesoParameter = vpeso.HasValue ?
                new ObjectParameter("vpeso", vpeso) :
                new ObjectParameter("vpeso", typeof(double));
    
            var vult_vis_pacParameter = vult_vis_pac.HasValue ?
                new ObjectParameter("vult_vis_pac", vult_vis_pac) :
                new ObjectParameter("vult_vis_pac", typeof(System.DateTime));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vobservaciones_pacParameter = vobservaciones_pac != null ?
                new ObjectParameter("vobservaciones_pac", vobservaciones_pac) :
                new ObjectParameter("vobservaciones_pac", typeof(string));
    
            var vest_pacParameter = vest_pac.HasValue ?
                new ObjectParameter("vest_pac", vest_pac) :
                new ObjectParameter("vest_pac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarPaciente", vnom_pacParameter, vcod_razaParameter, vfec_nac_pacParameter, vsexoParameter, vcod_colorParameter, vlongitudParameter, vpesoParameter, vult_vis_pacParameter, vfotoParameter, vobservaciones_pacParameter, vest_pacParameter);
        }
    }
}
