//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_HundeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Detalle_Consulta
    {
        public string cod_cons { get; set; }
        public int cod_trat { get; set; }
        public int cod_estado { get; set; }
        public string cod_med { get; set; }
        public string obs_det_cons { get; set; }
    
        public virtual Tb_Consulta Tb_Consulta { get; set; }
        public virtual Tb_Estado Tb_Estado { get; set; }
        public virtual Tb_Medicina Tb_Medicina { get; set; }
        public virtual Tb_Tratamiento Tb_Tratamiento { get; set; }
    }
}
