//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_HundeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Tratamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Tratamiento()
        {
            this.Tb_Detalle_Consulta = new HashSet<Tb_Detalle_Consulta>();
        }
    
        public int cod_trat { get; set; }
        public string tipo_trat { get; set; }
        public string nombre_trat { get; set; }
        public string cod_cat_trat { get; set; }
        public Nullable<int> estado_trat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Detalle_Consulta> Tb_Detalle_Consulta { get; set; }
    }
}
