//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_HundeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DetallesPaciente
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public string nom_raza { get; set; }
        public Nullable<System.DateTime> fec_nac_pac { get; set; }
        public Nullable<int> sexo { get; set; }
        public string color { get; set; }
        public Nullable<double> longitud { get; set; }
        public Nullable<double> peso { get; set; }
        public string conducta { get; set; }
        public string nutricion { get; set; }
        public string actividad { get; set; }
        public string observaciones { get; set; }
        public string det_obs { get; set; }
        public Nullable<int> estado { get; set; }
        public byte[] foto { get; set; }
    }
}
