//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyRaza {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Raza", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class Raza : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_razaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_razaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_raza {
            get {
                return this.cod_razaField;
            }
            set {
                if ((this.cod_razaField.Equals(value) != true)) {
                    this.cod_razaField = value;
                    this.RaisePropertyChanged("cod_raza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_tipo {
            get {
                return this.cod_tipoField;
            }
            set {
                if ((this.cod_tipoField.Equals(value) != true)) {
                    this.cod_tipoField = value;
                    this.RaisePropertyChanged("cod_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_raza {
            get {
                return this.nom_razaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_razaField, value) != true)) {
                    this.nom_razaField = value;
                    this.RaisePropertyChanged("nom_raza");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyRaza.IServicioRaza")]
    public interface IServicioRaza {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRaza/listarRazas", ReplyAction="http://tempuri.org/IServicioRaza/listarRazasResponse")]
        Win_Hunde.ProxyRaza.Raza[] listarRazas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRaza/listarRazas", ReplyAction="http://tempuri.org/IServicioRaza/listarRazasResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyRaza.Raza[]> listarRazasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRaza/listarRazasPorTipo", ReplyAction="http://tempuri.org/IServicioRaza/listarRazasPorTipoResponse")]
        Win_Hunde.ProxyRaza.Raza[] listarRazasPorTipo(short codTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRaza/listarRazasPorTipo", ReplyAction="http://tempuri.org/IServicioRaza/listarRazasPorTipoResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyRaza.Raza[]> listarRazasPorTipoAsync(short codTipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRazaChannel : Win_Hunde.ProxyRaza.IServicioRaza, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRazaClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyRaza.IServicioRaza>, Win_Hunde.ProxyRaza.IServicioRaza {
        
        public ServicioRazaClient() {
        }
        
        public ServicioRazaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRazaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRazaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRazaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Win_Hunde.ProxyRaza.Raza[] listarRazas() {
            return base.Channel.listarRazas();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyRaza.Raza[]> listarRazasAsync() {
            return base.Channel.listarRazasAsync();
        }
        
        public Win_Hunde.ProxyRaza.Raza[] listarRazasPorTipo(short codTipo) {
            return base.Channel.listarRazasPorTipo(codTipo);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyRaza.Raza[]> listarRazasPorTipoAsync(short codTipo) {
            return base.Channel.listarRazasPorTipoAsync(codTipo);
        }
    }
}
