//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_Hunde.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hunde")]
    [System.SerializableAttribute()]
    public partial class ClienteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidos_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cel_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccion_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dni_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string duenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string email_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short es_duenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short estado_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_reg_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ult_modificacion_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_ubigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usu_reg_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usu_ult_modificacion_cliField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cliente {
            get {
                return this.ape_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_clienteField, value) != true)) {
                    this.ape_clienteField = value;
                    this.RaisePropertyChanged("ape_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos_nombre {
            get {
                return this.apellidos_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidos_nombreField, value) != true)) {
                    this.apellidos_nombreField = value;
                    this.RaisePropertyChanged("apellidos_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cel_cliente {
            get {
                return this.cel_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.cel_clienteField, value) != true)) {
                    this.cel_clienteField = value;
                    this.RaisePropertyChanged("cel_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_cli {
            get {
                return this.cod_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_cliField, value) != true)) {
                    this.cod_cliField = value;
                    this.RaisePropertyChanged("cod_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion_cliente {
            get {
                return this.direccion_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.direccion_clienteField, value) != true)) {
                    this.direccion_clienteField = value;
                    this.RaisePropertyChanged("direccion_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni_cliente {
            get {
                return this.dni_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.dni_clienteField, value) != true)) {
                    this.dni_clienteField = value;
                    this.RaisePropertyChanged("dni_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dueno {
            get {
                return this.duenoField;
            }
            set {
                if ((object.ReferenceEquals(this.duenoField, value) != true)) {
                    this.duenoField = value;
                    this.RaisePropertyChanged("dueno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email_cliente {
            get {
                return this.email_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.email_clienteField, value) != true)) {
                    this.email_clienteField = value;
                    this.RaisePropertyChanged("email_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short es_dueno {
            get {
                return this.es_duenoField;
            }
            set {
                if ((this.es_duenoField.Equals(value) != true)) {
                    this.es_duenoField = value;
                    this.RaisePropertyChanged("es_dueno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short estado_cli {
            get {
                return this.estado_cliField;
            }
            set {
                if ((this.estado_cliField.Equals(value) != true)) {
                    this.estado_cliField = value;
                    this.RaisePropertyChanged("estado_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_reg_cli {
            get {
                return this.fec_reg_cliField;
            }
            set {
                if ((this.fec_reg_cliField.Equals(value) != true)) {
                    this.fec_reg_cliField = value;
                    this.RaisePropertyChanged("fec_reg_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ult_modificacion_cli {
            get {
                return this.fecha_ult_modificacion_cliField;
            }
            set {
                if ((this.fecha_ult_modificacion_cliField.Equals(value) != true)) {
                    this.fecha_ult_modificacion_cliField = value;
                    this.RaisePropertyChanged("fecha_ult_modificacion_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_ubigeo {
            get {
                return this.id_ubigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_ubigeoField, value) != true)) {
                    this.id_ubigeoField = value;
                    this.RaisePropertyChanged("id_ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cliente {
            get {
                return this.nom_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_clienteField, value) != true)) {
                    this.nom_clienteField = value;
                    this.RaisePropertyChanged("nom_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usu_reg_cli {
            get {
                return this.usu_reg_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.usu_reg_cliField, value) != true)) {
                    this.usu_reg_cliField = value;
                    this.RaisePropertyChanged("usu_reg_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usu_ult_modificacion_cli {
            get {
                return this.usu_ult_modificacion_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.usu_ult_modificacion_cliField, value) != true)) {
                    this.usu_ult_modificacion_cliField = value;
                    this.RaisePropertyChanged("usu_ult_modificacion_cli");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(Win_Hunde.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(Win_Hunde.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        Win_Hunde.ProxyCliente.ClienteBE ConsultarCliente(string strCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyCliente.ClienteBE> ConsultarClienteAsync(string strCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(Win_Hunde.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(Win_Hunde.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        bool EliminarCliente(string strCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(string strCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarClientes", ReplyAction="http://tempuri.org/IServicioCliente/ListarClientesResponse")]
        Win_Hunde.ProxyCliente.ClienteBE[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarClientes", ReplyAction="http://tempuri.org/IServicioCliente/ListarClientesResponse")]
        System.Threading.Tasks.Task<Win_Hunde.ProxyCliente.ClienteBE[]> ListarClientesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : Win_Hunde.ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<Win_Hunde.ProxyCliente.IServicioCliente>, Win_Hunde.ProxyCliente.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarCliente(Win_Hunde.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.InsertarCliente(objClienteBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(Win_Hunde.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.InsertarClienteAsync(objClienteBE);
        }
        
        public Win_Hunde.ProxyCliente.ClienteBE ConsultarCliente(string strCod) {
            return base.Channel.ConsultarCliente(strCod);
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyCliente.ClienteBE> ConsultarClienteAsync(string strCod) {
            return base.Channel.ConsultarClienteAsync(strCod);
        }
        
        public bool ActualizarCliente(Win_Hunde.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.ActualizarCliente(objClienteBE);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(Win_Hunde.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.ActualizarClienteAsync(objClienteBE);
        }
        
        public bool EliminarCliente(string strCod) {
            return base.Channel.EliminarCliente(strCod);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(string strCod) {
            return base.Channel.EliminarClienteAsync(strCod);
        }
        
        public Win_Hunde.ProxyCliente.ClienteBE[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<Win_Hunde.ProxyCliente.ClienteBE[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
    }
}
